### ISSUE TITLE
Feature request: check if a `float` or `double` is NaN

### ISSUE THREAD

**Issue by iamthad** [doctest/doctest#105]
Since NaN values don't compare equal to themselves, it doesn't work to do e.g.
```cpp
CHECK(someVar == std::numeric_limits<double>::quiet_NaN());
```
It works to use 
```cpp
CHECK(std::isnan(someVar));
```
but then `false` is printed if the test fails instead of the value of `someVar`.

It'd be nice to have a macro that tests that the value is NaN and displays its value if it is not.

**Comment by onqtam** [comment]
I'll add this to the roadmap :)

**Comment by Saalvage** [comment]
Added in dev!
