### ISSUE TITLE
--sc does not work if SUBCASE contains commas

### ISSUE THREAD

**Issue by blastrock** [doctest/doctest#135]
## Description
I have a subcase which contains a comma and I can't filter it with --sc. Moreover it was very troubling because the wrong test was run.

### Steps to reproduce

Here's a simple program:

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

TEST_CASE("tc") {
    SUBCASE("ab") {
        std::cout << "ab" << std::endl;
    }
    SUBCASE("ab, c") {
        std::cout << "abc" << std::endl;
    }
}
```

Run it with

    clang++ test.cpp -o test -std=c++14 && ./test --sc='ab, c'

You get "ab" instead of "ab, c"

### Extra information

This seems to be a feature to run multiple subcases, but it was quite misleading to me, I lost some time just to see that the wrong test was run.

I have two alternative suggestions to fix that:

- if the string is "ab, c" run all "ab", " c", and "ab, c" subcases
- or change the argument syntax so that if you want to run multiple subcases, you would type --sc='ab' --sc='cd'

---

* doctest version: master **cd1d747**
* Operating System: **debian unstable**
* Compiler+version: **clang 5.0.0**

**Comment by onqtam** [comment]
the same issue is true for filtering test cases by name - not just about subcases...

the reasoning behind this was to have a simple way of specifying multiple test cases (or subcases) to be executed - with a comma-separated string... but I guess having commas in the names should either:

- just work - including filtering
- trigger a warning/error at runtime (or perhaps I could use a constexpr parse of the test case/subcase name to check for ```,```)

I guess I should make it work - but I'm not sure how - without changing the semantics of the current filtering system...

**Comment by onqtam** [comment]
it seems that in Catch commas can be escaped and included in such searches - see this:
https://github.com/catchorg/Catch2/issues/1327#issuecomment-402970532

**Comment by onqtam** [comment]
I just thought of a workaround for the time being - use ```?``` instead of the commas (```,```)

**Comment by onqtam** [comment]
a PR which allows commas to be escaped was just merged, however I do think that this solution:
> or change the argument syntax so that if you want to run multiple subcases, you would type --sc='ab' --sc='cd'
would be better in the long term, so I'll keep this open

**Comment by cdeln** [comment]
Well, now the comma as a separator is part of the doctest binary interface, we can't change it without a breaking change.
This would be a change for version 3.xx, if this is even going to be considered.
Personally, I think the backslash escaping solution does the job just fine.

I suggest we either
1) Close this
2) Mark it for 3.xx with a new label
