### ISSUE TITLE
Micro benchmarking support

### ISSUE THREAD

**Issue by matt77hias** [doctest/doctest#251]
It would be nice to have support for micro benchmarking as well; ideally something with a similar level of detail as Nonius (e.g., confidence intervals). Google Test has the separate but similar Google Benchmark, and Catch2 will probably get a (boostless) [Nonius integration](https://github.com/catchorg/Catch2/pull/1616).

**Comment by onqtam** [comment]
Perhaps... in the future :) - this won't happen anytime soon. I looked at the Catch docs and this looks interesting - even having the ability to write benchmark sections within test cases:
https://github.com/catchorg/Catch2/blob/master/docs/benchmarks.md

**Comment by onqtam** [comment]
I just stumbled upon [this project](https://github.com/martinus/nanobench#advanced-example) which has an "integrating with doctest" section :)

**Comment by andersfylling** [comment]
nanobench doesn't seem to update their documentation. So it's extremely hard to figure out how to use it. Especially after the breaking change.

**Comment by onqtam** [comment]
@andersfylling Perhaps this example isn't out-of-date: https://github.com/martinus/nanobench/blob/master/docs/tutorial.md#comparing-results

**Comment by andersfylling** [comment]
Sadly, it is.

**Comment by Lectem** [comment]
I've had no news from martin through Github/Gitter, but I'm using nanobench in production with several changes.

I'm starting to think I should probably clean and push those modifications, update the docs until @martinus comes back.

**Comment by martinus** [comment]
Hi, sorry about being inactive for a while. I blame it on COVID stress... I hope to find more time soon and have a look at the issues that have accumulated. I know that the documentation is out of date, but I wanted to finish refactoring nanobench before I correct all the documentation. I hope to find more time in the coming weeks

**Comment by martinus** [comment]
Nanobench 4.0.0 is released! With to to date and extensive documentation at https://nanobench.ankerl.com
