### ISSUE TITLE
Test cases containing a comma cannot be run individually

### ISSUE THREAD

**Issue by Tradias** [doctest/doctest#297]
## Description
Trying to run a test binary which contains a test_case that has a comma in its name with `"--test-case=[name with comma]"` causes no test to run.

### Steps to reproduce
Create a test case with a comma, like   
`TEST_CASE("a,b") {}`
Run it with `"--test-case=a,b` and expect that test to execute.  
Likewise when running it with `"--test-case=a\,b"` which means `ctest` is also unable to run any tests when using the `doctest_discover_tests` cmake function.
Actual result: All tests are skipped.

### Extra information
I noticed that there is some special handling for commas in the `doctest_discover_tests` cmake script, yet even without it, I cannot get the test to run using `ctest`.
I am using this `main` entry point, even though I doubt it

* doctest version: **v2.3.5**
* Operating System: **Ubuntu 19.04**
* Compiler+version: **GCC 9.1 and Clang 8.0**

**Comment by onqtam** [comment]
here is a related issue around subcases and filtering of names with commas: https://github.com/onqtam/doctest/issues/135

so basically filtering has an issue around commas, but you can use ```?``` instead of ```,``` for now which basically means "match 1 character no matter what it is".

**Comment by onqtam** [comment]
a PR which allows commas to be escaped (with `\` as a prefix) was just merged in `dev`, however I do think that this solution (as proposed in #135 ):
> or change the argument syntax so that if you want to run multiple subcases, you would type --sc='ab' --sc='cd'

would be better in the long term, so I'll keep this issue open

**Comment by bevinhex** [comment]
Not only comma but also other special characters like ":",";" cause test to get skipped

**Comment by Tradias** [comment]
@bevinhex works fine for me with version 2.4.5 and 2.4.6

**Comment by bevinhex** [comment]
@Tradias Perhaps it is fixed on 2.4.5 then, I was using 2.4.4, because that is the latest version on conan center at the moment

**Comment by Saalvage** [comment]
Primary issue fixed, #135 will remain as the potential rest of this is figured out.
