### ISSUE TITLE
warning : function declared 'noreturn' should not return [-Winvalid-noreturn]

### ISSUE THREAD

**Issue by Vexthil** [doctest/doctest#307]
## Description
When compiling with the clang compiler this warning is reported if `DOCTEST_CONFIG_NO_EXCEPTIONS` is on.

`doctest.h(4369,5): warning : function declared 'noreturn' should not return [-Winvalid-noreturn]
`

This is the `[[noreturn]] void throw_exception(Ex const& e)` function

### Extra information

* doctest version: **v2.3.3**
* Operating System: **Windows**
* Compiler+version: **clang 9**

**Comment by onqtam** [comment]
well... to be fair the function never returns - it either throws an exception or calls ```std::terminate()``` - making a bunch of compilers and static analysis tools all happy at the same time is quite tedious...

I'll add clang 9 to the continuous integration and will silence this warning - thanks for reporting!

**Comment by Saalvage** [comment]
[Can't repro this warning at all](https://godbolt.org/z/Ts13z9hMj), might've been a compiler bug that was fixed? Either way, we're not currently silencing this warning and we have clang (9) CI so this can be closed!
