### ISSUE TITLE
[Feature] Better integration with tools (VS Code Test Adapter Extension)

### ISSUE THREAD

**Issue by wilhem-meignan** [doctest/doctest#320]
## Description

The "Catch2 and Google Test Explorer" Extension for Visual Studio Code has experimental support for doctest. However, several tests with the same name but in different tests suites can't be run. Also, the test results can't be displayed reliably inline in the source code. This could be fixed if some additional information was available from the command line.

Could you add the possibility to list the test suites and test cases with file names and line numbers from the command line?

This would make it possible for the extension to work reliably and give VS Code users much better usability while using doctest.

See: https://github.com/matepek/vscode-catch2-test-adapter/issues/143#issuecomment-566092840
And: https://github.com/matepek/vscode-catch2-test-adapter/issues/143#issuecomment-566139062

**Comment by onqtam** [comment]
Now that you've mentioned this - it seems obvious to provide the filename/line/testsuite along each test case when listing them in the xml reporter. I'll push a change for it ASAP - the new output will be here: https://github.com/onqtam/doctest/blob/dev/examples/all_features/test_output/list_test_cases_xml.txt

**Comment by matepek** [comment]
Hello,
Quick work! Forget to mention the "skipped" information, that would be useful too.
You already include a skipped attribute while the test runs. I mean It would be great to know which tests were marked as skipped by the user.

**Comment by onqtam** [comment]
@matepek I'll look into it... soon...

**Comment by wilhem-meignan** [comment]
Thank you both @onqtam & @matepek . That's great!

**Comment by onqtam** [comment]
@wilhem-meignan @matepek unfortunately I'll be able to get back to this sometime in January (to also list the skipped test cases).

**Comment by wilhem-meignan** [comment]
@onqtam OK. Thanks for the feedback.

**Comment by Trass3r** [comment]
In general, is there some kind of Catch2 compatibility mode so tools and scripts made for Catch2 could be used with doctest? For example there is also a Visual studio test runner which only supports the former.

**Comment by onqtam** [comment]
@Trass3r There is no switch that you can simply turn on for compatibility - you'd have to make a few changes as discussed in [the FAQ](https://github.com/onqtam/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-catch) - perhaps the biggest difference is that the ```TEST_CASE``` macro doesn't have tags in doctest so you'd have to either rewrite your test cases or redefine that macro so that it concatenates the name and tag strings as shown in the FAQ.

**Comment by Trass3r** [comment]
Yeah that's what I meant. If the command line interfaces were more compatible less changes would be needed in all those tools and scripts.

**Comment by Trass3r** [comment]
> You already include a skipped attribute while the test runs. I mean It would be great to know which tests were marked as skipped by the user.
> 
> Just to be clear: I mean the skipped="true" attribute for tests with `* doctest::skip()` for test listing.
> 
> Also "testsuite" attribute has to be included at "running tests" stage too to identify the test case uniquely.

Has that been implemented?

**Comment by onqtam** [comment]
@Trass3r not yet... that's why I still haven't closed the VSCode-related issues. I'll re-prioritize this in my doctest backlog and hopefully, I get to it by the end of this summer.

**Comment by Trass3r** [comment]
I'll test the extension with doctest. Has worked nicely with gtest so far. I esp. love the CodeLens feature.

**Comment by bilderbuchi** [comment]
The missing skipped attribute reporting just resurfaced again: https://github.com/matepek/vscode-catch2-test-adapter/issues/283#issuecomment-930352846

**Comment by bilderbuchi** [comment]
Does adding the skipped attribute imply a lot of changes? I guess it's more involved than adding `.writeAttribute("skipped", in.data[i]->m_skip);` [here](https://github.com/doctest/doctest/commit/b3d12b6588ef4235eabbf58f55480b6db0c4c187#diff-827303eb2723dee2a91483138781932f3cb7002ffb36ef199106b50e09b1aeeeR2086)?

**Comment by onqtam** [comment]
@bilderbuchi you are right - just pushed to `dev` and will soon be released in `master`.

@matepek 
> Also "testsuite" attribute has to be included at "running tests" stage too to identify the test case uniquely.

Anything more you need regarding test suites? I don't think I've done what was being promised here 1-2 years ago but maybe you have solved your issues somehow?

**Comment by matepek** [comment]
There are one more thing. In case of xml output it I had to write my own logic to decide that a test is failed or passed because the modifiers (ex.: doctest::expected_failures(1)) are not considered. 
So i checked the output of console format and translated the logic [here](https://github.com/matepek/vscode-catch2-test-adapter/blob/master/src/framework/DOCExecutable.ts#L456)

Also, I remember that I added some difference because it seemed more logical but I don't remember the case.
So there might be some debatable logic. And it would be nice to have the evaluated value: passed/failed.
In the `OverallResultsAsserts`.

**Comment by onqtam** [comment]
@matepek done - just added the `test_case_success` boolean attribute to the `OverallResultsAsserts` tag at the end of every test case - it's taking into account the decorators such as may/should fail & expected failures as coded in `finalizeTestCaseData()`: https://github.com/doctest/doctest/blob/1d86f2aff8f055296c01e28e3bc5013264c9d68c/doctest/parts/doctest.cpp#L499-L501

Regarding the logic of how to count a success/failure in the presence of decorators - it's tricky and there may indeed be different ways to do it which all seem logical from some point of view, but at least now the framework reports how it's reasoning about them.

**Comment by matepek** [comment]
From my side  in the next release the TestMate C++ vscode extension will respect the attribute. 🙏

**Comment by onqtam** [comment]
Ok, then I'm closing this
