### ISSUE TITLE
stringify of cstring literals doesn't work out of the box with separate test_driver.cpp

### ISSUE THREAD

**Issue by teichert** [doctest/doctest#329]
## Description
The following example compares a string object against a c-string literal.
The overloaded `==` operator ensures that the comparison is done character by character,
and doctest correctly prints the observed **"bad"** string as well as the expected **"expected"** c-string.

tests.cpp:
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include <string>

TEST_CASE("transfer") {
    std::string bad = "bad";
    // make a failing test
    REQUIRE(bad == "expected");
}
```
`g++ tests.cpp; ./a.out` gives the following expected output:
```
[doctest] doctest version is "2.3.6"
[doctest] run with "--help" for options
===============================================================================
tests.cpp:5:
TEST CASE:  transfer

tests.cpp:8: FATAL ERROR: REQUIRE( bad == "expected" ) is NOT correct!
  values: REQUIRE( bad == expected )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |      0 skipped
[doctest] assertions:      1 |      0 passed |      1 failed |
[doctest] Status: FAILURE!
```

However, if I separate out the test-driver into it's own test-driver.cpp:
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
```
Taking the `#define DOTEST_CONFIG...` out of tests.cpp:
```c++
#include "doctest.h"
#include <string>

TEST_CASE("transfer") {
    std::string bad = "bad";
    // make a failing test
    REQUIRE(bad == "expected");
}
```
`g++ test-driver.cpp tests.cpp; ./a.out` does not printed the c-string literal (notice the **{?}** rather than **"expected"**):
```
[doctest] doctest version is "2.3.6"
[doctest] run with "--help" for options
===============================================================================
tests.cpp:4:
TEST CASE:  transfer

tests.cpp:7: FATAL ERROR: REQUIRE( bad == "expected" ) is NOT correct!
  values: REQUIRE( bad == {?} )

===============================================================================
[doctest] test cases:      1 |      0 passed |      1 failed |      0 skipped
[doctest] assertions:      1 |      0 passed |      1 failed |
[doctest] Status: FAILURE!
```

## Work Around
If I `#include <iostream>` (e.g. right after `#include <string>`), then stringify works again.

## Comments
At first I thought that avoiding the extra include inside of doctest.h might be intentional.  If that is the case, then maybe an entry in the FAQ page with an explanation and workaround would be helpful.

### Extra information
* doctest version: **v2.3.6**
* Operating System: **Ubuntu 18.4**
* Compiler+version: **g++ 7.4.0**

**Comment by onqtam** [comment]
Indeed the ```<string>``` include is avoided intentionally... But this is an inconvenient and surprising bug - I might have to re-evaluate my decision not to include that header... At least it's just about formatting and not correctness and there is an easy workaround. I'll put an entry in the FAQ. Thanks for reporting this!

**Comment by teichert** [comment]
Great; thanks! (And thanks the amazing framework!)
Just to be clear, I think this issue isn't specifically about the `<string>` header since one *could* get the same type of behavior in the following (contrived) example:
```c++
#include "doctest.h"

TEST_CASE("test") {
    // a failing test case
    REQUIRE("pointer" == "equality");
}
```
Also, I realized that the work-around really only needs `#include <ostream>` rather than `<iostream>`.  (btw, for reference on the compilation-work impact of including the ostream header, I checked the size of the output from the preprocessor and compiler (no-linking) for this most recent example above and found that adding `#include <ostream>` increases the resulting preprocessed cpp from 41K to 654K while the resulting object file goes from 14K to 15K in size.)

**Comment by onqtam** [comment]
For the pointer equality thing you could use [```DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING```](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_treat_char_star_as_string)

**Comment by Saalvage** [comment]
This should be fixed in dev! (If it somehow isn't please reopen!)
