### ISSUE TITLE
CHECK_MESSAGE() should accept temporaries

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#337]
If I `CHECK_MESSAGE(my_cond, function_returning_a_string())`, I get the error:
```
error: static assertion failed with "Cannot pass temporaries or rvalues to the streaming operator because it caches pointers to the passed objects for lazy evaluation!"
```
Well, if doctest can detect when I've passed a temporary or an rvalue, then - instead of just caching the pointer, doctest can make a copy, regardless of whether the condition checked out. That is in keeping of what the user wants...

**Comment by onqtam** [comment]
Thanks for reporting and sorry for the late reply! This could indeed be solved but I cannot promise when - for now, I'd advise using a local variable.

**Comment by Saalvage** [comment]
This appears to have been fixed at some point!
