### ISSUE TITLE
Add option not to print the intro text

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#342]
doctest currently has an option not to print the version, so that `printVersion()` starts with:
```
         void printVersion() {
             if(opt.no_version == false)
```
I suggest that the same option be added for the intro text, i.e.
```
        void printIntro() {
+            if(opt.no_intro == false) {
             printVersion();
             // etc. etc.
+            }
 ```
and a corresponding command-line option be added. Sometimes you just want your binary to be more quiet...

**Comment by onqtam** [comment]
The ```no-version``` option is probably useful only for me - so that I don't have to update a bunch of reference test output each time I release a new version.

I guess there should be a concept of verbosity - perhaps one would want to also not see the stats in the end if everything has passed successfully?

**Comment by eyalroz** [comment]
@onqtam : I would be ok with either a "no intro" option or a single "no intro and no version" option. An overall "quiet" option is useful, but some people (like me) do want to see the summaries on success, without the intro.

**Comment by onqtam** [comment]
One possible thing to do without editing the doctest header would be to inherit from the ```ConsoleReporter``` class in the ```.cpp``` wherever the test runner is being implemented, override the ```test_run_start()``` method without calling the intro printing and then register your new reporter & use that.

I'll release 2.3.7 without this, but I'll keep the issue open for perhaps the next version because I want to think it through.

**Comment by eyalroz** [comment]
Are you discussing what _you_ could do, what test authors could do, or what test runners could do? It seems like it's the middle one.

Also - no rush of course. It's not like something is broken.

**Comment by onqtam** [comment]
I meant that wherever the test runner is implemented (```DOCTEST_CONFIG_IMPLEMENT```) you could inherit in that same translation unit from the console reporter and make a new one with this tiny change, but then you'd have to also always use ```my_console``` instead of ```console``` as the reporter - perhaps with a default ```main()``` function.

**Comment by eyalroz** [comment]
Well, you could offer the same thing for all sorts of options... I'd hope test authors don't have to know about "console reporters" and such.

**Comment by onqtam** [comment]
Just rolled it in its simplest form as you suggested - seems obvious in retrospect - not sure why I didn't make it the simplest possible way and be done with it...
