### ISSUE TITLE
No reset to std::dec for printing the test summary table

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#343]
I'm using v2.3.0 .

If I set `std::hex`  on cout somewhere in the testcode, doctest does not reset this to `std::dec` for printing its test summary. I think that it should.

**Comment by eyalroz** [comment]
Are you sure that `std::dec` is enough? I mean, are there no other ios flags you need to make sure and set?

**Comment by onqtam** [comment]
From what I saw I couldn't figure out how to fully reset the ios flags of a stream (maybe I glossed over it). Any idea how? I'd reopen this and properly fix it for the next version.

It's also advisable for people who change these flags to use RAII so that they reset them when the RAII guard goes out of scope...

**Comment by Saalvage** [comment]
Huh, well this says exactly the opposite from the comment on #229! So still only `std::dec` is being set, I think we should either reset all or none. Thoughts?

**Comment by eyalroz** [comment]
Adapting my comment from #229 

* doctest _should_ isolate its ios flags from those of the test code, i.e. if the code I'm testing sets `std::hex`, doctest should not produce hexadecimal numbers for its own output (test indicates, number of passing jobs etc)
* doctest should allow setting some/all ios flags for its own output - using some separate, dedicated mechanism (either exposing a stream or via getters/setters which work with `ios_base::fmtflags` values).

**Comment by cdeln** [comment]
I think we can close this in favor of keeping #229 as a discussion thread for this issue.

**Comment by eyalroz** [comment]
@cdeln : Sure.
