### ISSUE TITLE
How to do a check with a logical OR

### ISSUE THREAD

**Issue by erelsgl** [doctest/doctest#353]
## Description

When I try to make a check with a logical OR operator, I get a compiler assertion claiming that the expression is too complex.

### Steps to reproduce

    CHECK(factorial(3)==5 || factorial(3)==6)

### Extra information

I can solve the problem by writing a boolean function, e.g.:

    bool is_5_or_6(int i) { return i==5 || i==6; }

and then use it:

    CHECK(is_5_or_6(factorial(3)))

But it is cumbersome. Is there a better way to do it?

**Comment by onqtam** [comment]
For now you could surround the expression with parenthesis like this: ```CHECK( (factorial(3)==5 || factorial(3)==6) );```
