### ISSUE TITLE
the dll example doesn't run correctly on Windows with MinGW

### ISSUE THREAD

**Issue by GregKon** [doctest/doctest#375]
Hi

I have try to run self test based on cmake.
1. Mingw, gcc 9.2.0 64bits, failed 2 test with dll
```
      Start 63: executable_dll_and_plugin
63/66 Test #63: executable_dll_and_plugin ...............***Failed    0.34 sec
      Start 64: executable_dll_and_plugin_xml
64/66 Test #64: executable_dll_and_plugin_xml ...........***Failed    0.33 sec
```
2. Visual studio 2017, builds ok but all 68 test failed.
```
cmake -H. -B_builds -G "Visual Studio 15 2017"
cmake --build .
ctest -C Release
```
Could someone help me understand/make it run?
/Greg

**Comment by onqtam** [comment]
Did you have any issues with `v2.3.7` when running the test? I can't think of any important change between `v2.3.7` and `v2.3.8` that would result in such failures...

**Comment by GregKon** [comment]
Hi

version 
[results.txt](https://github.com/onqtam/doctest/files/4661012/results.txt)
2.3.8.
1. VS2017: it now working OK, when generate and run exactly as is in log from link you point me.

2. Mingw 64bit:
cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug
cmake --build .
(so far all good)

ctest --output-on-failure
produce erros with 2 tests, attached file.

**Comment by onqtam** [comment]
and can you confirm that this happens only in version `2.3.8` and not in `2.3.7`?

**Comment by GregKon** [comment]
I have tested 2.3.8 only.

**Comment by Saalvage** [comment]
MinGW CI succeeds, so assuming this fixed!
