### ISSUE TITLE
Compile error on MSVC2019 with any macro which involves stringification of std::string (asserts, INFO, etc.) when <ostream> isn't included

### ISSUE THREAD

**Issue by nyanpasu64** [doctest/doctest#381]
## Description

If I compile doctest v2.3.8 on MSVC 2019, 

I don't know if this issue was caused by updating doctest or MSVC. I didn't experience the issue on doctest v2.3.4 with an older MSVC, but newer MSVC and latest C++ mode breaks older doctest. And when trying to downgrade doctest and build using C++17 mode, Qt Creator crashed and I'm trying to debug that.

This issue seems somewhat related to https://github.com/onqtam/doctest/issues/356, but I'm getting a compilation error rather than linking error.

### Steps to reproduce

```
#include <doctest.h>
#include <string>

TEST_CASE("test") {
    std::string foo;
    INFO(foo);
}
```

Resulting errors:

https://gist.github.com/nyanpasu64/4c93792cdbf02b5c02700fddf7c64df5

### Extra information

* doctest version: **2.3.8**
* Operating System: **Windows 10 x64**
* Compiler+version: **MSVC 2019 x64 14.26.28801 or 16.6.30114.105 or 19.26.28805 (not sure)**

**Comment by onqtam** [comment]
I think this would again be fixed by just including either `<ostream>` or `<iostream>` - MSVC 2019 changed their internal header structure and I remember filing a bug about that (but it won't be fixed because the change has been intentional). Unfortunately I can't find the bug or the other doctest issue which linked to that bug...

**Comment by nyanpasu64** [comment]
https://github.com/onqtam/doctest/commit/1ea91445686768a1216e03815433962cd4b8681d was found as soon as 2.3.3. But I upgraded doctest from 2.3.4 (which already had the fix) to 2.3.8, and MSVC at the same time, causing my compile issue.

I ended up including <ostream>, but why does that fix not work?

**Comment by onqtam** [comment]
oh - because for that you'd need to define `DOCTEST_CONFIG_USE_STD_HEADERS` before the doctest header

**Comment by blockspacer** [comment]
```cpp
// `#define INFO` from DOCTEST
// conflicts with macros from other libs
#define DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES
```

**Comment by onqtam** [comment]
@blockspacer is this related to the issue?

**Comment by blockspacer** [comment]
> @blockspacer is this related to the issue?

I got similar error, also with INFO macro. fixed by DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES

**Comment by onqtam** [comment]
@blockspacer I think these are 2 separate issues - you just have conflicting macros with other libraries and indeed the right approach for you is to use `DOCTEST_CONFIG_NO_SHORT_MACRO_NAMES`. This issue however is completely different - it's related to the way doctest stringifies expressions and detects `operator<<(std::ostream&...)` for types.

**Comment by Saalvage** [comment]
This has been fixed in dev. :)
