### ISSUE TITLE
reduce code size

### ISSUE THREAD

**Issue by Trass3r** [doctest/doctest#404]
There are a few functions which could be made inline to reduce code size, e.g.  SubCase operator bool.
One could even try to [optimize](https://github.com/Trass3r/doctest/commit/4611bae881f840ff858ec4910b8254b2139efdac) for string literals.

**Comment by onqtam** [comment]
I'd be interested in some numbers before considering such a change because moving all function definitions out of the interface part of the header was done explicitly in order to improve compile times ==> less weak duplicated symbols for the linker to resolve throughout different object files if the header is included in more than one place (+ the functions get compiled only once - in the implementation of doctest). There would need to be significant code size reductions (although I'm not sure what significant means here...)

**Comment by Trass3r** [comment]
What do you use as compile time benchmarks?

**Comment by onqtam** [comment]
I used [these scripts](https://github.com/onqtam/doctest/tree/master/scripts/bench) to generate [the benchmarking page](https://github.com/onqtam/doctest/blob/master/doc/markdown/benchmarks.md) but the scripts are pretty horrible (python 2 vs 3 problems, etc) and the last time I ran the benchmarks locally I had to do some steps manually and comment out some parts... Not particularly proud of that part of the codebase :|

At some point I just annotated all functions in the interface part `noinline` but they were still defined there, and got some improvements in build times: https://github.com/onqtam/doctest/issues/70

Later on, I also moved them entirely out of the interface part of the header (commit https://github.com/onqtam/doctest/commit/35c9336f56c2f821a782dcc58456bd190a14208e ), but it was about only 10% improvement in the cost of including the header (meaning that it went down from probably 20ms to 18ms for a single `.cpp` which would matter only if you have thousands of `.cpp` files including it...). Now that I think about it... that's some extreme premature optimization which is borderline insane & a waste of time back then. I'd be willing to move some of the functions back into the interface part (still with `noinline` attributes) if the code size reduction is meaningful, but I think there are bigger fish to fry IMHO.

**Comment by Trass3r** [comment]
Yes maybe something like https://github.com/ldionne/metabench should be used.
Though I don't like that dependency on Ruby.

**Comment by cdeln** [comment]
I believe that moving things back into the interface is against the goals of this project.

I am also interested in seeing numbers here before even discussing making a change (and those numbers need to be very convincing IMO).

I suggest we close this as a wont fix.
