### ISSUE TITLE
Conflict with templated toString function

### ISSUE THREAD

**Issue by TillHeinzel** [doctest/doctest#420]
## Description
Defining a templated toString function that is ADL discoverable conflicts with the StringMaker overload of toString in the library:
```c++
template <typename T>
String toString(const DOCTEST_REF_WRAP(T) value) {
    return StringMaker<T>::convert(value);
}
```
### Steps to reproduce
```c++
#include <doctest.h>
namespace A
{
    struct X{};

    bool operator==(const X&, const X&) { return false; }

    template<class T>
    std::string toString(T t)
    {
        return {};
    }
}

TEST_CASE("testing")
{
    REQUIRE(A::X{} == A::X{});
}
```

### Extra information
doctest: 2.4.0
OS: Windows 10
Compiler: Visual studio 16.7.3 

My thoughts on how to fix it:
I have not looked at the code too deeply, but I am guessing the conflicting overload is supposed to act purely as a default, in case no overload was provided by the user. For that case, I would hack the overload by adding an indirection e.g. toString_call that would then try calling toString, and only call the StringMaker if the first try failed.

**Comment by zeux** [comment]
We're hitting what looks like more or less the same issue, but without the templated part. We have an existing codebase where some pointer types have a `std::string toString(X);` in the same namespace. When using this type in the comparison with nullptr we hit an issue where in stringifyBinaryExpr, one of the operands converts to a std::string and another one converts to doctest::String, and you can't add them together.

**Comment by Saalvage** [comment]
I really don't see a way of fixing this.
However, it does appear this is a slightly construed example, as I'm unsure of when you'd want to actually just override a random subset of stringifications with `{}`. For all practical purposes partially specializing `StringMaker` or providing `operator<<` should do the trick!
