### ISSUE TITLE
Provide an error message if REQUIRE (or other disabled assertion macros) are used when exceptions are disabled

### ISSUE THREAD

**Issue by alexeyr** [doctest/doctest#439]
## Description
Instead of undefining `REQUIRE` and related macros completely when exceptions are disabled, can a error message be emitted? I just learned `cl.exe` doesn't enable exception handling by default while trying to figure out how `DOCTEST_REQUIRE` could fail to be found.

**Comment by onqtam** [comment]
Well... I think that undefining `REQUIRE` by default when exceptions are disabled is good enough...

Alternatively, the `REQUIRE` macro could instead be changed to emitting an `#error` pragma using `__pragma()` - I'll keep this issue open and might do it at some point.

**Comment by Saalvage** [comment]
`static_assert` to the rescue!

**Comment by Saalvage** [comment]
Implemented in dev!

**Comment by yeputons** [comment]
@Saalvage 
Looks like there is a `\` missing [here](https://github.com/doctest/doctest/blob/94b52bb66753f33ee422d60eda459bfb865c3ae0/doctest/doctest.h#L2740-L2741), my VS complains when compiling the example from #633:

```
C:\Users\yeputons\Documents\tmp3\doctest.h(2741): error C2059: syntax error: 'string'
C:\Users\yeputons\Documents\tmp3\doctest.h(2741): error C2059: syntax error: ')'
C:\Users\yeputons\Documents\tmp3\doctest.h(2741): error C2059: syntax error: 'return'
C:\Users\yeputons\Documents\tmp3\doctest.h(2741): error C2059: syntax error: '}'
C:\Users\yeputons\Documents\tmp3\doctest.h(2741): error C2143: syntax error: missing ';' before '}'
a.cpp(5): error C3409: empty attribute block is not allowed
a.cpp(5): error C2059: syntax error: '{'
a.cpp(5): error C2143: syntax error: missing ';' before '{'
a.cpp(5): error C2059: syntax error: ';'
a.cpp(8): fatal error C1004: unexpected end-of-file found
```

I also suspect that this may warrant adding some CI tests

**Comment by Saalvage** [comment]
@yeputons Huh, I have a really hard time telling where the `\` is supposed to be missing?
Also CI for something that *should* fail to compile seems really tedious to add so I will not be doing hat for 2.4.9.

**Comment by yeputons** [comment]
@Saalvage just at the end of 2740, otherwise the compiler (VS, GCC) thinks the macro ends on 2740 and yields an "invalid syntax" error.

>  Also CI for something that should fail to compile seems really tedious to add so I will not be doing hat for 2.4.9.

Ah, yeah, makes sense.

**Comment by Saalvage** [comment]
@yeputons Thanks for catching that, stupid me!
