### ISSUE TITLE
[Coverity] Concurrent data access violations (MISSING_LOCK) doctest.h: 5838 in doctest::<unnamed>::ConsoleReporter::test_case_start(const doctest::TestCaseData &)()

### ISSUE THREAD

**Issue by jiridanek** [doctest/doctest#486]
## Description
```
/qpid-dispatch/tests/c_unittests/doctest.h: 5838 in doctest::<unnamed>::ConsoleReporter::test_case_start(const doctest::TestCaseData &)()
5832             }
5833     
5834             void test_case_start(const TestCaseData& in) override {
5835                 hasLoggedCurrentTestStart = false;
5836                 tc                        = &in;
5837                 subcasesStack.clear();
>>>     CID 363731:  Concurrent data access violations  (MISSING_LOCK)
>>>     Accessing "this->currentSubcaseLevel" without holding lock "doctest::<unnamed>::ConsoleReporter.mutex". Elsewhere, "_ZN7doctest11_GLOBAL__N_15ConsoleReporterE.currentSubcaseLevel" is accessed with "doctest::<unnamed>::ConsoleReporter.mutex" held 2 out of 3 times (1 of these accesses strongly imply that it is necessary).
5838                 currentSubcaseLevel = 0;
5839             }
5840             
5841             void test_case_reenter(const TestCaseData&) override {
5842                 subcasesStack.clear();
5843             }
```

### Steps to reproduce
Run Coverity Scan on doctest. When doctest is vendored into a project, it is desirable that it passes all the same checks/lints/... the project does. Here is the Coverity page for Apache Qpid Dispatch from which the above originates https://scan.coverity.com/projects/apache-qpid-dispatch-router?tab=overview. There are some additional diagnostics there, but accessing that requires signup. I guess the issue can be triaged from the report above. And then either suppressed or fixed.

### Extra information
* doctest version: **v2.4.6**

**Comment by onqtam** [comment]
Subcases should not be used concurrently and that's stated in the docs - if a test case spawns threads then the only thing that's allowed are asserts and logging macros. Is Coverity static analysis or dynamic? If static, then this is a false positive. If dynamic - then that's a wrong use of the library.

**Comment by onqtam** [comment]
I'll add the appropriate annotations if you give me a patch or open a PR :)

**Comment by jiridanek** [comment]
```
        void subcase_end() override {
            std::lock_guard<std::mutex> lock(mutex);
            --currentSubcaseLevel;
            hasLoggedCurrentTestStart = false;
        }
```

Can you explain why the lock is necessary here? I'm willing to figure out adding the suppressions, but I am not 100% convinced the report is a false positive. On the other hand, I would not be unreasonable to simply accept expert opinion on the matter (yours I mean ;P).

**Comment by onqtam** [comment]
Actually I'll take a closer look at this tomorrow as I've forgotten some things - that lock guard in `subcase_end` surprised me :D

**Comment by onqtam** [comment]
Ok, so I refreshed my memory a bit. All threads spawned within a subcase should be joined by the end of it (as shown [here](https://github.com/doctest/doctest/blob/master/examples/all_features/concurrency.cpp)) and no new subcases should be opened - I just pushed some comments that clarify that in the docs. The use of a mutex in subcase start/end is just a nice-to-have addition in case someone uses subcases and threads in a more convoluted way that is actually discouraged by the docs but might save them from problems.

There can't be a race in `test_case_start` in any way (unless a user hasn't joined a thread from a previous test case) so I do think that's a false positive - the tool simply reasons by analogy when it looks at which variables are protected in other methods. I'll simply add a lock there as well just to avoid having to deal with such reports in the future from other tools.

**Comment by jiridanek** [comment]
This sounds like it should help. The way I work with Coverity does not easily allow running on anything other than the main branch of my project.

I see that your change is now in release https://github.com/doctest/doctest/releases/tag/2.4.7, so I'll simply upgrade doctest in the project.

**Comment by onqtam** [comment]
Let me know when you get to try it!

**Comment by jiridanek** [comment]
I finally made sense of all that. We set the warning database on the Coverity website to exclude warnings for test code. So it sends e-mails about new finds, but it does not show them in the webui afterwards. I managed to check that the previous warning is really marked fixed.

Thanks for looking into this!
