### ISSUE TITLE
[Feature request] CHECK could return the value of expression

### ISSUE THREAD

**Issue by Lectem** [doctest/doctest#496]
## Description

It would be nice to have `CHECK` (or a new macro) returning the result of the expression.
This is something I've for assertions in quite a few code bases where I have a "VERIFY" assert that is evaluated no matter what and can participate in the flow of the program.
In the case of doctest, simlarly to `VERIFY` vs `ASSERT`, CHECK does not stop the execution (while REQUIRE does) I think it would make sense that `CHECK` also returns the evaluation of the condition so that we can write code such as this:

```cpp
if(CHECK(somePtr != nullptr))
{
     CHECK(somePtr->someMember == someValue);
}
```

So that one can avoid this kind of code:
```cpp
CHECK(somePtr != nullptr);
if(somePtr != nullptr)
{
     CHECK(somePtr->someMember == someValue);
}
```

This is very helpful when dealing with optional data when writing a test that can handle different inputs with the same code.

Is this something you would be interesting in supporting ?

**Comment by onqtam** [comment]
This will be quite hard to achieve (if possible at all) while maintaining the expression decomposing semantics of the `CHECK` macro. Maybe an easy solution is to have a global (thread local) variable set by the framework which can then be queried - something like `if(doctest::LastAssertFailed)`

**Comment by onqtam** [comment]
This was just implemented by @Saalvage & merged in `dev`! Closing this issue.
