### ISSUE TITLE
compiling doctest in 32-bit with __stdcall calling convention fails

### ISSUE THREAD

**Issue by BeErikk** [doctest/doctest#500]
## Description
compiling doctest in 32-bit with __stdcall calling convention gives the following two error messages

`doctest.h(4264): error C2440: '=': cannot convert from '_crt_signal_t' to 'void (__stdcall *)(int)'`
`doctest.h(4264): note: This conversion requires a reinterpret_cast, a C-style cast or function-style cast`
`doctest.h(4298): error C2664: '_crt_signal_t signal(int,_crt_signal_t)': cannot convert argument 2 from 'void (__stdcall *)(int)' to '_crt_signal_t'`
`doctest.h(4298): note: This conversion requires a reinterpret_cast, a C-style cast or function-style cast`
`signal.h(62): note: see declaration of 'signal'`

the problem could be solved with the following patch:

[doctest-gitdiff-cdecl.txt](https://github.com/onqtam/doctest/files/6368904/doctest-gitdiff-cdecl.txt)

Possibly also by defining a well known macro substitution `CDECL` for example
```
#ifndef CDECL
#define CDECL __cdecl
#endif
```

### Steps to reproduce
compile doctest in 32-bit with __stdcall calling convention

### Extra information

* doctest version: **git current**
* Operating System: **Windows 10**
* Compiler+version: **Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914**

**Comment by BeErikk** [comment]
or
```
#if !defined(CDECL) && defined(_WIN32)
#define CDECL __cdecl
#else
#define CDECL
#endif
```

**Comment by onqtam** [comment]
> or
> 
> ```
> #if !defined(CDECL) && defined(_WIN32)
> #define CDECL __cdecl
> #else
> #define CDECL
> #endif
> ```

would that cause problems for 64 bit mode?

**Comment by BeErikk** [comment]
> > or
> > ```
> > #if !defined(CDECL) && defined(_WIN32)
> > #define CDECL __cdecl
> > #else
> > #define CDECL
> > #endif
> > ```
> 
> would that cause problems for 64 bit mode?

No, as far as I understand `_WIN32` is defined by the MS compiler in x86, x64 and ARM and surely by most other well-known compilers as well. FYI not to be confused with the `WIN32` define which is defined by the user. In 64-bit both `_WIN32` and `_WIN64` is defined by the compiler but the latter is rarely used.

[MSDN: Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)

**Comment by onqtam** [comment]
I meant adding `__cdecl` in 64 bit builds as I'm not familiar enough with calling conventions

**Comment by BeErikk** [comment]
> I meant adding `__cdecl` in 64 bit builds as I'm not familiar enough with calling conventions & if it would cause problems with stdcall & whatnot

No, it doesn't matter. You can add any calling convention prefix to suit your needs `__cdecl`, `__stdcall`, `__fastcall` etc. As far as I understand all 64-bit compiles become `__fastcall` regardless anyway. In 32-bit, the `__stdcall` calling convention is commonly used by Microsoft libraries and tools. The issue usually becomes a problem when functions that take function pointers as parameters are supplied with function pointers without a specified calling convention, that is functions are defined without a calling convention and rely on the underlying calling convention which usually is `__cdecl` but sometimes is `__stdcall`.

The solution in this case is thus:
`void (CDECL *FatalConditionHandler::prev_sigabrt_handler)(int);`

[MSDN: __cdecl](https://docs.microsoft.com/en-us/cpp/cpp/cdecl?view=msvc-170)

**Comment by onqtam** [comment]
pushed in `dev`
