### ISSUE TITLE
[FEATURE REQUEST] Quiet flag

### ISSUE THREAD

**Issue by gamagan** [doctest/doctest#503]
Please add a 'quiet' flag where Doctest shows none of its usual output.

My particular usecase is that I use Doctest for testing a 3D Renderer. I run each testcase individually, and each test runs twice: once for setting up the test frame data, and another time to verify the rendered frame. Since each test is ran individually, and each test runs twice, the console contains lots of noise from Doctest's usual output. 

* doctest version: 2.4.5
* Operating System: Windows 10, 64bit
* Compiler+version: MSVC 2019, latest

**Comment by gamagan** [comment]
I managed to get the behavior that I wanted(on Windows 10) by doing:
`doctest::Context::setOption("out", "NUL")`
on the Context instance.

**Comment by onqtam** [comment]
That redirects the output to a file and indeed can be used as a workaround. Leaving this open for now

**Comment by onqtam** [comment]
2 new flags pushed in `dev` branch (soon in official version in `master):
- `-quiet` - quiets everything regardless
- `-minimal` - outputs only on failure

Closing this - let us know if these aren't sufficient!
