### ISSUE TITLE
variable maximum is assigned 6206517616395625 instead of the actual return value which is 5.0

### ISSUE THREAD

**Issue by kk723** [doctest/doctest#530]
## Description
I'm trying to get a basic unit test working with c++ using doctest. I'm using doctest because redditors on r/CPP have been saying doctest is one of the easier unit testing frameworks to learn and get started with. 

### Steps to reproduce
In my [code](https://pastebin.com/d99p0swt), I was able to get the second test to pass with my function testBasicReturn(), but I'm not able to get the first test to pass with findMax(values, size). This function is also basic. Given an array, return the highest value in the array, which should be 5. But the test keeps failing. For some reason, it thinks the variable "maximum" equals 6206517616395625. It seems so basic that maximum should equal 5, but it's not returning that. Here is the link to the full code: https://pastebin.com/d99p0swt

This seems like a bug because the variable maximum shouldn't be assigned such a long integer value when the function findMax(values, size) returns 5.0 in my main() function. 

```
g++ -std=c++11 01-findMax.cpp && ./a.out
[doctest] doctest version is "2.4.6"
[doctest] run with "--help" for options
===============================================================================
01-findMax.cpp:24:
  Scenario: All combinations of numbers should return the max
     Given: 1, 2, 3, 4, 5

01-findMax.cpp:30: ERROR: CHECK( maximum == 5.0 ) is NOT correct!
  values: CHECK( 62065176163956259725479625737468007090208417468147454124858474888371003793749484461928484180739965426803497188434660452381478397268680744483085852534201589091401787813457377377117040756800193721485229072661496283528511356928.0 == 5.0 )

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 2 | 1 passed | 1 failed |
[doctest] Status: FAILURE!
```

### Extra information

Doctest version: 2.4.6

Operating System
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```
Compiler
```
$ which g++
/usr/bin/g++
$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by onqtam** [comment]
Sorry it took me so long to look at your issue - it appears that the pastebin code examples have expired - can you provide the code here in the issue?

**Comment by Saalvage** [comment]
Closing due to a lack of response. If this is still an issue please reopen!
