### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by DominicD** [doctest/doctest#537]
I saw that the last commit was on dev branch in April. Also a lot of open pull request that are quite old.
So basically I just want to know if it is still maintaned.

Thanks

**Comment by yudi-azvd** [comment]
Almost it is still maintained. If im not mistaken the creator is quite busy at work or something, so he said doctest development would slow

**Comment by onqtam** [comment]
I took a long break from it but it is still maintained and a new version should roll out soon!

**Comment by onqtam** [comment]
Actually, I've been thinking of passing the torch for quite a while and I just pulled the trigger - [this is the announcement](https://github.com/doctest/doctest/issues/554) for anyone interested! I'll stick around for the next couple of months and do 1-2 more releases but won't be able to do it for much longer - more details in that issue.

**Comment by onqtam** [comment]
It will be maintained going forward - see [this](https://github.com/doctest/doctest/issues/554#issuecomment-1009162545) for more context. Closing!
