### ISSUE TITLE
Regression between 2.4.6 and 2.4.7 with Visual Studio 2015

### ISSUE THREAD

**Issue by nlohmann** [doctest/doctest#573]
## Description

The project [nlohmann/json](https://github.com/nlohmann/json) uses Doctest for years. I created https://github.com/nlohmann/json/pull/3228 to update to the latest version 2.4.7. However, the tests with Visual Studio 2015 all fail, see https://ci.appveyor.com/project/nlohmann/json/builds/42035862.

Build log: [log.txt](https://github.com/doctest/doctest/files/7792030/log.txt)

### Steps to reproduce

- Checkout `develop` branch of [nlohmann/json](https://github.com/nlohmann/json)
- Replace file `test/thirdparty/doctest/doctest.h` with that of Doctest 2.4.7
- Compile test suite with Visual Studio 2015

### Extra information

* doctest version: **v2.4.7**
* Operating System: **Windows-6.3.9600**
* Compiler+version: **MSVC 19.0.24241.7, Build Engine version 14.0.25420.1**

**Comment by onqtam** [comment]
This will be fixed with the next version!

**Comment by onqtam** [comment]
Fixed in the dev branch - will release an official version soon!

**Comment by nlohmann** [comment]
Any estimation when 2.4.8 will be released?

**Comment by onqtam** [comment]
I think it will be up to a week.
