### ISSUE TITLE
[meta] Change git tagging pattern

### ISSUE THREAD

**Issue by iboB** [doctest/doctest#579]
git-based package managers and tools often expect the repo tags for versions to be in the form of the version number prepended with "v" (as in `v1.2.3`) and there is an unwritten "rule" in GitHub that this is preferred way to tag versions.

Using tags of this form will make the integration of doctest in such toolchains easier and make it more like many other GitHub projects.

**Comment by onqtam** [comment]
Will change with the next release, thanks!

**Comment by YarikTH** [comment]
It looks funny, because "nlohmann/json" had the opposite issue with Conan version ranges not working because of "v".
https://github.com/nlohmann/json/issues/2409

**Comment by iboB** [comment]
as put by one of the commenters in the link:

> IMHO it is conan's job to support v prefixes.

😁
