### ISSUE TITLE
Update roadmap following maintainer change

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#581]
Following the announcement closing #554 , I'd like to ask @Saalvage to update the roadmap to account for their priorities/interests/intentions.

**Comment by Saalvage** [comment]
I think I'll wait just a little longer to address that once all "immediate" issues have been dealt with (so after v2.4.9's release).
In the meantime I'll just use this to collect some thoughts for things I want for v2.5:
- Splitting the two monolithic doctest files up into more managable chunks (while keeping it single header for release)
- STL stringification
- Clean up all the code coverage, docs, benchmarks and whatnot (I might do this one before v2.5)

**Comment by Saalvage** [comment]
So I've decided to move the roadmap to an issue of its own in order to facilitate discussion. You can find it and give your thoughts here: #600
