### ISSUE TITLE
Feature request: option to disable fallback "{?}" stringifier

### ISSUE THREAD

**Issue by YarikTH** [doctest/doctest#591]
## Description

Without properly set up stringification of all tested types doctest become less helpful.
Compare https://godbolt.org/z/jnq7WM5hb

```c++
TEST_CASE("Wtf?") {
    int i1 = 2;
    int i2 = 3;

    CHECK(i1 == i2);

    std::array<int, 3> a1 = { 1, 2, 3 };
    std::array<int, 3> a2 = { 2, 2, 3 };

    CHECK(a1 == a2);
}
```

```
<source>:10: ERROR: CHECK( i1 == i2 ) is NOT correct!
  values: CHECK( 2 == 3 )

<source>:15: ERROR: CHECK( a1 == a2 ) is NOT correct!
  values: CHECK( {?} == {?} )
```

Unfortunately, the fact that type stringification is missing is not so easily foundable. Need to manually pass -s and find "{?}" throughout the output.

Little option to replace 
```c++
        template <typename T>
        static String convert(const DOCTEST_REF_WRAP(T)) {
            return "{?}";
        }
```
with
```c++
        template <typename T>
        static String convert(const DOCTEST_REF_WRAP(T)) {
            static_assert(false, "No stringification rules are detected for type T. See  string conversions manual");
            return "{?}";
        }
```
would be helpful to find all broken places and fix them.

**Comment by Saalvage** [comment]
I'm wondering if this is actually ever an issue in practice. Usually I'd assume you find a `{?}` in a failed test output and as a consequence of that you go ahead and implement string conversions for that type.

Are you actually using this in practice or would want to use it in practice or is this just intended to be a "nice-to-have" thing? The amount of config options is already quite daunting and I think it's preferable to only add new ones that would actually have use in practice.

**Comment by YarikTH** [comment]
I would use it in practice, but I can do it in my own copies of doctest if I wish, so it's more or less a "nice-to-have" thing. If options add pain in maintaining a library then it seems that it is not worth it.

I didn't do it so far, despite it being trivially doable, so it is obviously not so important for me.

It won't be a problem at all if I either:
* do a proper TDD. Make a failed test first, see its stringified output, fix stringification, move forward
* do fix stringification just as I see it is broken instead "I'll do it later (no)"

But I don't so the absence of compile-time checks of stringification bothers me a little, but not at a level when I am ready to actually do something with it.

**Comment by Saalvage** [comment]
This is enough justification Imo. I might have overstated the pain in adding more flags. We probably just have to organize them better!

**Comment by Saalvage** [comment]
When it comes to a config macro, I propose `DOCTEST_CONFIG_REQUIRE_STRINGIFICATION_FOR_ALL_USED_TYPES`, thoughts?

**Comment by YarikTH** [comment]
Long, but very hard to misunderstand. I like it.

**Comment by Saalvage** [comment]
Merged! 😄
