### ISSUE TITLE
Loop-generated `SUBCASE`s are not run

### ISSUE THREAD

**Issue by yeputons** [doctest/doctest#597]
## Description

If the same `SUBCASE` line is used for multiple root subcases in the test, only the first one is run.

### Steps to reproduce

Run the following example:

```c++
#include "doctest.h"
#include <iostream>

TEST_CASE("generated subcases") {
    std::cout << "root" << std::endl;
    for (int i = 0; i < 3; i++) {
        std::cout << "outside of subcase" << std::endl;
        SUBCASE("") {
            std::cout << "inside subcase " << i << std::endl;
        }
    }
}
```
it prints

```
root
outside of subcase
inside subcase 0
outside of subcase
outside of subcase
root
outside of subcase
outside of subcase
outside of subcase
```

Note that there is extra run of `TEST_CASE` which does not enter any `SUBCASE`s. Moreover, `i = 1` and `i = 2` are not executed at all.
 
I'd expected this example to be equivalent to

```c++
#include "doctest.h"
#include <iostream>

TEST_CASE("generated subcases") {
    std::cout << "root" << std::endl;
    std::cout << "outside of subcase" << std::endl;
    SUBCASE("") {
        std::cout << "inside subcase " << 0 << std::endl;
    }
    std::cout << "outside of subcase" << std::endl;
    SUBCASE("") {
        std::cout << "inside subcase " << 1 << std::endl;
    }
    std::cout << "outside of subcase" << std::endl;
    SUBCASE("") {
        std::cout << "inside subcase " << 2 << std::endl;
    }
}
```

which prints

```
root
outside of subcase
inside subcase 0
outside of subcase
outside of subcase
root
outside of subcase
outside of subcase
inside subcase 1
outside of subcase
root
outside of subcase
outside of subcase
outside of subcase
inside subcase 2
```

### Extra information
It seems to me that `SUBCASE` actually remember its `__FILE__` and `__LINE__`, and presumably uses this information to check whether or not a subcase has been executed. However, it's possible to do without this information, purely control-based approach.

Possible usecases are very similar to parameterized tests. For example, I use it to test behavior of smart pointer implementations in school assignments, like this:

```c++
TEST_CASE("unique_ptr reset") {
    for (int orig_non_empty = 0; orig_non_empty < 2; orig_non_empty++) {
        INFO("orig_non_empty is " << orig_non_empty);

        SUBCASE("") {
            unique_ptr<int> p(orig_non_empty == 1 ? new int(10) : nullptr);
            int *raw_p = nullptr;
            SUBCASE("no arguments") {
                p.reset();
            }
            SUBCASE("to nullptr") {
                p.reset(raw_p);
            }
            SUBCASE("to a new pointer") {
                raw_p = new int(20);
                p.reset(raw_p);
            }

            REQUIRE(p.get() == raw_p);
            if (raw_p != nullptr) {
                REQUIRE(p);
                CHECK(&*p == raw_p);
            } else {
                REQUIRE(!p);
            }
        }
    }
}
```

* doctest version: **v2.4.6**
* Operating System: **Windows 10 Pro 21H1**
* Compiler+version: **g++ (Rev5, Built by MSYS2 project) 11.2.0**

**Comment by yeputons** [comment]
Note: some reuse of `SUBCASE` is allowed, the following example works as expected:

```c++
#include "doctest.h"
#include <iostream>

TEST_CASE("reused subcases") {
    std::cout << "root" << std::endl;
    auto test = [](int arg) {
        std::cout << arg << std::endl;
        SUBCASE("x.1") {
            std::cout << arg << ".1" << std::endl;
        }
        SUBCASE("x.2") {
            std::cout << arg << ".1" << std::endl;
        }
    };
    SUBCASE("1") {
        test(1);
    }
    SUBCASE("2") {
        test(2);
    }
}
```

prints

```
root
1
1.1
root
1
1.1
root
2
2.1
root
2
2.1
```

This is the work-around I'm currently using.

**Comment by Saalvage** [comment]
Thank you for the very detailed report!

[This branch](https://github.com/doctest/doctest/tree/fix-subcase-reentry) should fix your issue.

> It seems to me that SUBCASE actually remember its __FILE__ and __LINE__, and presumably uses this information to check whether or not a subcase has been executed. However, it's possible to do without this information, purely control-based approach.

Would you mind sharing the rough idea behind such an approach? I'd be interested in hearing it.

**Comment by yeputons** [comment]
@Saalvage,

> Would you mind sharing the rough idea behind such an approach? I'd be interested in hearing it.

Sure thing. Here is a model:

1. I assume each `TEST_CASE` has a fixed rooted tree of all `SUBCASE`s to be executed. We would like to preserve the original semantics: execute each leaf exactly once, executing its parents on our way to the leaf. We also don't want to deal with any kind of self-modifying tree because the semantics becomes wobbly.
2. Now, if we just execute `TEST_CASE` with all `SUBCASE`s, we will get depth-first-search traversal of the tree. What we want instead is to "save" state of the depth-first-search on reaching a leaf and then go directly for the next one.
3. More formally, we have (or have to implement) the following operations:
    * `test_case_body()` — executes `TEST_CASE`, provided by the user.
    * `bool enter_subcase();` — executed in `SUBCASE`'s guard variable constructor. `SUBCASE` is entered iff the function returns `true`. Provided by us.
    * `void exit_subcase()` — executed in `SUBCASE`'s guard variable destructor. Provided by us.
    * `void run_test_case()` — executed by the test runner to run `TEST_CASE` with all `SUBCASE`s. Provided by us.
    * Now we have to add some thread-local variable with some state modified by `enter_subcase`/`exit_subcase`.
4. Unfortunately, we don't know the tree's structure beforehand. At the beginning we only know about the root of tree. However, each `enter_subcase()` call reveals us that there is another child. If we return `false`, we skip this child. If we return `true`, we go to this child and start traversing its children.
5. One can assign `vector<int>` (stack, actually) for each child: `{}` for the root, `{0}`/`{1}`/... for its children, `{1, 0}`/`{1, 1}`/`{1, 2}` for the second child's children, etc.
6. Now you can track its position in the tree of `SUBCASE`s using a stack. Whenever you encounter leaf (i.e. you exit a vertex and the maximal depth of a visited vertex is the current one), you enter a separate state: do not enter any other children, remember the next child you meet instead (or remember that there are no children to traverse). Once you've exited `TEST_CASE`, you can remember the next child to execute and re-run `TEST_CASE`, skipping all children lexicographically smaller than the child you want to execute.

It may get surprisingly tricky to understand all these invariants and get a concise code. I recommend lots of drawing. Turns out, you only need tree vectors which keep track of the current vertex, the vertex you want to visit next, and the vertex after that. Plus a `size_t` and a `bool`, or something like this. No need to store a set of all visited tests, their IDs or anything like this.

I'm hesitant to share full code with this exact wording on a public forum because that was actually a home assignment for my freshmen students this fall, which I assumed was already implemented by doctest :) Would be happy to share the code along with some tests via email or by adding you a private repository for inspiration.

**Comment by Saalvage** [comment]
After finally getting the chance to investigate this a bit more I'm fairly certain that implementing the proposed soluton is not as easy as it first appears.

Assuming you have
```cpp
for (int i : { 0, 1, 2 }) {
    cout << "outside of subcase" << endl;
    SUBCASE("") { cout << "inside subcase " << i << endl; }
    SUBCASE("") { cout << "also inside " << i << endl; }
}
```
in order to successfully determine that the first subcase is not actually a third subcase after the second one has been selected for execution seems to require maintaining a mapping of `SubcaseSignature`s to their corresponding stack representation. In praxis this would probably be approximately equally as expensive as maintaining the entire history.

I may be missing something here, but I believe by simply storing the hashes of completed stacks, as I've done in the latest commit, we'll have a near-optimal design.

**Comment by Saalvage** [comment]
Closing as the primary issue has been resolved, but I'd still be very much interested in learning about whether I am right about the necessity of the loop-prevention measures I've put in place!

**Comment by yeputons** [comment]
> in order to successfully determine that the first subcase is not actually a third subcase after the second one has been selected for execution

Hmm, but does it matter? The logic should not depend on `SubcaseSignature`s at all, IMHO. Their names and location in the code should not be important, only their execution flow should.

>  I am right about the necessity of the loop-prevention measures I've put in place!

The test looks good. I would like to take a look at the logic itself at some point, but not sure about any timelines.

For future readers: the following code with recursive subcases works in doctest 2.4.8, prior to this patch:

```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

void recursive_subcase(int level, int id) {
    if (level == 2) {
        MESSAGE("id=" << id);
        CHECK(id != 21);
        return;
    }
    SUBCASE("1") { recursive_subcase(level + 1, id * 10 + 1);}
    SUBCASE("2") { recursive_subcase(level + 1, id * 10 + 2);}
};

TEST_CASE("Test") {
    recursive_subcase(0, 0);
}
```

As far as I understand, the only thing that does not work is when the same `SUBCASE` statement tries to generate multiple subcases on the same stack.
