### ISSUE TITLE
Update Doctest in vcpkg to 2.4.8

### ISSUE THREAD

**Issue by gc435** [doctest/doctest#604]
vcpkg currently has Doctest 2.4.6.  I'm not sure who the appropriate person is to update it to 2.4.8, but it seems pretty simple:

https://github.com/microsoft/vcpkg/tree/master/ports/doctest

**Comment by onqtam** [comment]
anyone can submit a PR there

**Comment by YarikTH** [comment]
IANM. but as I can see there is no single person that is responsible for it.
https://github.com/microsoft/vcpkg/pulls?q=is%3Apr+doctest+

Every PR with an update was done by a different person. So you may either do it yourself or wait for someone done it somewhen.

As I understand, library maintainers typically don't maintain a zoo of packages for their libraries.

**Comment by gc435** [comment]
What does IANM mean?

**Comment by YarikTH** [comment]
I Am Not Maintainer. So my answer might be incorrect due lack of knowledge.

**Comment by JesseHines0** [comment]
There's a PR to update the vcpkg repository now (https://github.com/microsoft/vcpkg/pull/23081).

**Comment by Saalvage** [comment]
PR has been merged!
