### ISSUE TITLE
tagging convension has changed?

### ISSUE THREAD

**Issue by kloczek** [doctest/doctest#605]
My automationa reliest on git tag. 
During manual checking astatus of doctest module I found that it is new release but tagging convention has changes from `<version>` to `v<version>`.
Is that tagging going to be new one or it was mistake? 🤔

**Comment by onqtam** [comment]
yep, it was changed in purpose: https://github.com/doctest/doctest/issues/579

**Comment by kloczek** [comment]
Thx. Closing 😄
