### ISSUE TITLE
Internal compiler error with GCC 7.5

### ISSUE THREAD

**Issue by foonathan** [doctest/doctest#606]
## Description

After upgrading to 2.4.8, I had various internal compiler errors with GCC 7.4: https://github.com/foonathan/lexy/runs/4998385826?check_suite_focus=true

### Steps to reproduce

I've minimized the first one to the following code:

```cpp
#include <doctest.h>

struct type
{
    operator bool() const;
};

TEST_CASE("foo")
{
    constexpr type obj{};
    CHECK(obj);
    CHECK(obj);
    CHECK(obj); // only the third one fails
}
```
https://godbolt.org/z/bdjqPxos9

### Extra information

* doctest version: **v2.4.8**
* Operating System: **Linux**
* Compiler+version: **gcc 7.5**

**Comment by foonathan** [comment]
If that helps, I've preprocessed the example and ran it through creduce, this is a minimal source code that reproduces the compiler bug: https://godbolt.org/z/3dPf9cs55

It seems GCC 7 doesn't like constexpr variables being captured in multiple lambdas. Maybe the change to use IILE can be reverted for that compiler?

(The switch to using lambdas also broke my code where I'm using an assertion for the value of a structured binding member, as those can't be captured by lambdas in C++17)

**Comment by Saalvage** [comment]
Current dev head has reverted IILE's as the standard way to handle scopes, giving a config flag to enable them. I feel like that'll be enough?
Thanks for the report!

**Comment by foonathan** [comment]
Yes, that would work for me. Thank you!

Out of curiosity, what's the reason for switching to IILE? Is it just implementation convenience or do I get an advantage that way?

**Comment by Saalvage** [comment]
It allows assertions to return their result, as requested in #496. ^^

Closing 👍

**Comment by foonathan** [comment]
Ah, makes sense. Are you planning on tagging another release with it? That way I'll get notified when the fix is live.

**Comment by Saalvage** [comment]
Yep, v2.4.9 will hopefully release this month.

**Comment by foonathan** [comment]
Any update on a release?

**Comment by Saalvage** [comment]
I'm terribly sorry, life has very much gotten in the way of things.. I will try my best to make the release this month.

**Comment by foonathan** [comment]
Don't worry about it; I just need to workaround #473 in my locally copy as I can't update due to CI failures yet, so I just wanted to ask.
