### ISSUE TITLE
Regression: Clang-Tidy warnings in 2.4.8

### ISSUE THREAD

**Issue by nlohmann** [doctest/doctest#607]
## Description

When updating the test suite of [nlohmann/json](https://github.com/nlohmann/json), several Clang-Tidy warnings had to be silenced:

- cert-err58-cpp
- cppcoreguidelines-avoid-c-arrays
- fuchsia-statically-constructed-objects
- hicpp-avoid-c-arrays
- llvm-else-after-return
- modernize-avoid-c-arrays
- readability-else-after-return

(see https://github.com/nlohmann/json/pull/3228/files#diff-0534891fbc8b89b4c521057e7e8dff70d3cbeb822cc9991a3abad77848c289f8 for the suppressions and https://github.com/nlohmann/json/runs/4719931709?check_suite_focus=true for the failed run)

### Steps to reproduce

- Check out develop branch of https://github.com/nlohmann/json
- Replace `test/thirdparty/doctest/doctest.h` with Doctest 2.4.8
- Compile the tests suite with Clang-Tidy

### Extra information

* doctest version: **v2.4.8**
* Operating System: **Ubuntu 20.04.3 LTS**
* Compiler+version: **Clang 14.0.0**

**Comment by nlohmann** [comment]
Does anyone need further information to proceed on this issue?

**Comment by Saalvage** [comment]
Nope, I already started resolving it, but I'd like to wait before the stringification refactor is merged in order to not have to go over everything again. I've also been busy with a ton of other stuff, but who isn't? I'm fairly certain I'll be able to release a fix for this within the month!

**Comment by nlohmann** [comment]
No need to rush - I just wanted to make sure you have all you need. I just wanted to avoid adding all the exclusion to my code base...

**Comment by nlohmann** [comment]
Any update on this?

**Comment by Saalvage** [comment]
This is what's kind of holding me back from releasing 2.4.9.. I'm struggling to find a good way of testing clang-tidy under the Windows environment I'm using. Regular clang fails at building some obscure Windows headers when using `clang-tidy` on the CLI and the clang tidy integrated with Visual Studio takes an incredibly unreasonable amount of time.
At first I thought that working via CI wouldn't work either, but considering that ideally it'd just spit out a list of all issues I think I will consider doing just that.
Sorry for the wait (again)!

**Comment by nlohmann** [comment]
I see. Do you need help setting up a CI job running Clang-Tidy? We have this target

https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L644

and search for Clang-Tidy with

https://github.com/nlohmann/json/blob/develop/cmake/ci.cmake#L21

We are using an individual Docker image for the CI, but I guess some Clang-Tidy version should also be available in GitHub's default Ubuntu runners.

Let me know if I can support.

**Comment by Saalvage** [comment]
So I've set up a separate GH actions task [here](https://github.com/doctest/doctest/blob/e2e4a7408b901d0062f3a4570f3c907828713234/.github/workflows/main.yml#L32). However, only `clang-analyzer-cplusplus.NewDeleteLeaks` are being detected (see [here](https://github.com/doctest/doctest/runs/6432178238?check_suite_focus=true)).

I'm honestly not sure what to attribute this to..
- I highly doubt that all other issues that clang-tidy raises for your project have been fixed at this point in time.
- It might be related to a lack of specifying the checks to execute? However, I don't see your specification of the checks anywhere either, so I have to assume you're using the standard as well.

Any clues?

**Comment by Saalvage** [comment]
At a loss on how to fix this at this point. https://github.com/doctest/doctest/runs/6478031779?check_suite_focus=true
```cpp
#define DOCTEST_TEST_SUITE_END                                                                     \
    DOCTEST_GLOBAL_NO_WARNINGS(DOCTEST_ANONYMOUS(DOCTEST_ANON_VAR_),                               \
            /* NOLINTBEGIN(cert-err58-cpp) */                                                      \
            doctest::detail::setTestSuite(doctest::detail::TestSuite() * ""))                      \
            /* NOLINTEND(cert-err58-cpp) */                                                        \
    using DOCTEST_ANONYMOUS(DOCTEST_ANON_FOR_SEMICOLON_) = int
```
I've also marked the `operator*` declaration with `NOLINT`, yet still no salvation in sight.

I'm aware that marking the method with `noexcept` would fix it, but I'm honestly not really eager to attach this attribute (which can be semantically meaningful) to something incorrectly, only to silence a clang-tidy warning..

**Comment by Saalvage** [comment]
@nlohmann Any idea on how to resolve this ideally?

**Comment by Saalvage** [comment]
After a lot of blood, sweat and tears I can finally tick this off the 2.4.9 pre-release checklist.

I've tested the fixed version with your project and it does not emit the warnings anymore!

Thank you for sticking with us!

**Comment by nlohmann** [comment]
Thanks for your efforts! Any rough timeline for the 2.4.9 release?

**Comment by Saalvage** [comment]
This was the last "major" fix. There are like 3 more open PRs that I'd like to merge and then we're good to go. I'm aiming for a release this week.

**Comment by Saalvage** [comment]
And it's here!
I'm really sorry for the horrendous delay.
And thank you for sticking with doctest! :)

**Comment by nlohmann** [comment]
Thanks a lot! I'm trying in https://github.com/nlohmann/json/pull/3545.

Keep up the good work!

**Comment by nlohmann** [comment]
The Clang-Tidy warnings are gone!

Unfortunately, there is now another issue with IPCC: https://github.com/doctest/doctest/issues/664

**Comment by Saalvage** [comment]
Could you try defining `_MSC_VER` and `_MSC_FULL_VER` to 0?
If not, are you only interested in using full releases? If not I could release a quick prerelease containing a fix, I was planing on doing that either way.
