### ISSUE TITLE
Feature request: CHECK_THROWS_WITH with contains option

### ISSUE THREAD

**Issue by MFraters** [doctest/doctest#619]
## Description
Currently CHECK_THROWS_WITH only checks if the string exactly matches the exception string. I would like to add a version which checks whether the exception contain a certain string. This is the same functionality as Catch2 `CHECK_THROWS_WITH(func(),Contains("needle"))`. 

I looked at the code and I think it could be implemented by adding a macro `CHECK_THROWS_WITH_CONTAINS` and adds in the ResultBuilder::log() something like (which worked locally for me): 
```
        } else if(m_at & assertType::is_throws_with_contains) { //!OCLINT bitwise operator in conditional
            m_failed = strstr(m_exception.c_str(), m_exception_string) == nullptr;
```

I am happy make a pull request if something like this would be an acceptable addition.

**Comment by Saalvage** [comment]
Imo we have way too many assertion macros as is, and I'm pretty opposed to adding any more. The way Catch2 probably implements this is via a wrapper around the string, similar to Approx (and more recently added, IsNaN). This seems like the most reasonable option, although it'll require some tinkering with the `ResultBuilder` (probably making `m_exception_string` a union of `String` and the new `Contains` class). PRs in that direction are very welcome!
