### ISSUE TITLE
doctest_discover_tests no longer sets ENVIRONMENT variables for discovered tests. 

### ISSUE THREAD

**Issue by quantumsteve** [doctest/doctest#621]
## Description

The CMake function `doctest_discover_tests` no longer sets ENVIRONMENT variables for discovered tests. This worked as recently as 2.4.5, but not in later versions.

### Steps to reproduce

I created a self-contained repro that checks the SOURCE_DIR environment variable isn't empty. The test passes with doctest 2.4.5 and fails with later versions.
https://github.com/quantumsteve/doctest_example

```
mkdir build
cd build
cmake ..
make
ctest
```

### Extra information

* doctest version: **v2.4.6 and later**
* Operating System: **Ubuntu 20.04**
* Compiler+version: **CMake 3.22.2, GCC 9.3.0**

**Comment by Saalvage** [comment]
After some superficial research I couldn't really determine anything obvious that would've changed this behavior. If you have more insight into this, please feel free to PR!

**Comment by quantumsteve** [comment]
I ran git bisect and the first "bad" commit is [680d0448bd7b6d221879e9dd0a2f2e9d9be64108](https://github.com/doctest/doctest/commit/680d0448bd7b6d221879e9dd0a2f2e9d9be64108).

**Comment by Saalvage** [comment]
Fixed in dev!
