### ISSUE TITLE
string comparison leads to gotting stuck

### ISSUE THREAD

**Issue by laoshaw** [doctest/doctest#622]
## Description

when below code runs the executable will get stuck will nothing printed out and it never exit.

1. DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING does not impact the result(with or without)
2. if failed CHECK is removed that it runs fine.
3. whenever there is a failed case it gets stuck.

### Steps to reproduce

file1.cpp: 

```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_TREAT_CHAR_STAR_AS_STRING  // with or without it's the same result XXX
#include <doctest.h>
```
file2.cpp:

```
#include <doctest.h>
#include <string.h>
TEST_CASE((strrchr(__FILE__, '/') + 1) * doctest::timeout(5.0)) {
    CHECK("XYZ"=="XYZ");
    CHECK("XYZ"=="XXYZ"); // XXX if this line is removed it works fine
}
```

```
g++ -Wall file1.cpp file2.cpp
./a.out
```

### Extra information

newest release 2.4.8 on ubuntu 20.04 with g++-11

**Comment by Saalvage** [comment]
Could you check if the bug can be reproduced with [this library version](https://raw.githubusercontent.com/doctest/doctest/fix-insertion-op/doctest/doctest.h)?

**Comment by laoshaw** [comment]
yes I can reproduce, the symptom remains to be the same.

**Comment by laoshaw** [comment]
I did notice if I change file2.cpp to:

```cpp
#include <doctest.h>
#include <string.h>
TEST_CASE("some tests") {
    CHECK("XYZ"=="XYZ");
    CHECK("XYZ"=="XXYZ"); // XXX if this line is removed it works fine
}
```
this it fails as expected and not got stuck, somehow the args to TEST_CASE() does not get along with mismatched strings.

**Comment by Saalvage** [comment]
What I suspect is happening here is that `strrchr` is returning `nullptr` due to `/` not occuring in `__FILE__`. You could verify this by printing out `__FILE__` as well as `(strrchr(__FILE__, '/') + 1)` like so:
```cpp
#include "doctest.h"
#include <string.h>
#include <iostream>
TEST_CASE((strrchr(__FILE__, '/') + 1) * doctest::timeout(5.0)) {
    std::cout << __FILE__ << std::endl;
    std::cout << (strrchr(__FILE__, '/') + 1) << std::endl;
    CHECK("XYZ"=="XYZ");
    CHECK("XYZ"=="XXYZ"); // XXX if this line is removed it works fine
}
```

**Comment by laoshaw** [comment]
I think it's the case here. Maybe this can be closed?
