### ISSUE TITLE
wasm*-support?

### ISSUE THREAD

**Issue by FrozenSource** [doctest/doctest#624]
Hi guys,

I am trying to compile a doctest'ed test program using the clang-wasm32-wasi target.
As far as I know and could found atomics and threading is not yet supported.

My problem is dat doctest seem to use a lot of std::atomic which (quote):
```error: <atomic> is not supported on this single threaded system```

I use the following arguments to clang:
```--target=wasm32-wasi --sysroot /tmp/wasi-sdk-sysroot-14.0 -D_WASI_EMULATED_SIGNAL```

Is there a possibility of supporting wasm builds? I'd hate to have to move to gtest or something for obvious reasons.

Sincerely,

**Comment by Saalvage** [comment]
Could you test if the `config-no-atomics` branch combined with `DOCTEST_CONFIG_NO_ATOMICS` allows you to compile?

**Comment by FrozenSource** [comment]
Thanks for that; this seems to fix the problems with the atomics classes.
As a follow up I am confronted with errors on std::mutex since it seems to have been commented out in the wasi-abi.
All the reporters seem to use this.

**Comment by FrozenSource** [comment]
This is my little config list using the following fork: https://github.com/FrozenSource/doctest/tree/config-no-atomics 
```
#define DOCTEST_CONFIG_NO_EXCEPTIONS
#define DOCTEST_CONFIG_NO_POSIX_SIGNALS
#define DOCTEST_CONFIG_NO_ATOMICS
#define DOCTEST_CONFIG_NO_MULTI_THREADING
#define DOCTEST_BREAK_INTO_DEBUGGER()
using Dtor = void(*)(void*);
C_FUNCTION inline int __cxa_thread_atexit(Dtor, void*, void*) {

    return 0;
}
#include <doctest/doctest.h>
```
I haven't tested everything yet like with for example the BREAK_INTO_DEBUGGER()... but this way it builds and runs :)

**Comment by Saalvage** [comment]
I'm gonna add this to my branch as well!

Are you aware of any preprocessor macros that wasm specifically defines? That way we could make it work straight out of the box.

**Comment by FrozenSource** [comment]
the llvm toolchain at the very least (I used the clang/clang++ fronted) provides the __wasi__ macro just like unix and linux.
https://reviews.llvm.org/rGc1eee1d659155b99fac63cbf72491c27106f0481

**Comment by Saalvage** [comment]
I've gone ahead and disabled the appropriate features automatically. It should be working out of the box now. (Except `__cxa_thread_atexit`, I have to admit I have no idea what that does exactly 😅)

If you figure out a way to break into the debugger using WASI please let me know!

**Comment by FrozenSource** [comment]
the ```__cxa_thread_atexit``` is at the ABI's way of cleaning up thread_local's. As such just like old-MSVC:
```
#ifndef DOCTEST_THREAD_LOCAL 
  #if (DOCTEST_MSVC && (DOCTEST_MSVC < DOCTEST_COMPILER(19, 0, 0)) )
    #define DOCTEST_THREAD_LOCAL 
  #else // DOCTEST_MSVC
    #define DOCTEST_THREAD_LOCAL thread_local
   #endif // DOCTEST_MSVC 
#endif // DOCTEST_THREAD_LOCAL
```
It should be disabled in both the header as the cpp file. Then it doesn't require it.

**Comment by Saalvage** [comment]
I see! Pushed a fix that should disable it automatically.

**Comment by Saalvage** [comment]
Do you have another chance to test the branch? If it's working as expected I would be able to merge it into dev ^^

**Comment by FrozenSource** [comment]
My build server saids green; I only still use DOCTEST_CONFIG_NO_EXCEPTIONS since I build for all platforms as well... thank you very much!

**Comment by Saalvage** [comment]
Merged in dev!
