### ISSUE TITLE
Decompose expressions containing the spaceship operator

### ISSUE THREAD

**Issue by falbrechtskirchinger** [doctest/doctest#629]
doctest seems to be missing support for the C++20 spaceship or 3-way comparison operator `<=>`.

Expressions containing the operator decompose as: `{?} == {?}`

https://godbolt.org/z/xcMn3fEY8

**Comment by onqtam** [comment]
isn't the real operator in this case `==`? the spaceship is in braces

**Comment by onqtam** [comment]
if you want something other than `{?}` to be printed you should teach doctest about the `std::strong_ordering` type as shown here: https://github.com/doctest/doctest/blob/master/doc/markdown/stringification.md

**Comment by Saalvage** [comment]
Also, what practical use does this serve over simply using `>`?

I'm not wholly familiar with how expressions are decomposed, but I think decomposing nested expressions might very well be either a nightmare or totally unachievable. And using `<=>` proper in an assertion directly fails to transmit a meaning to me (e.g. what would you expect from `CHECK(1 <=> 2)`?)

P.S.: `std::strong_ordering` will be one of the type's stringifiable in the v2.5 stl stringification extension header ;)

**Comment by falbrechtskirchinger** [comment]
> isn't the real operator in this case `==`? the spaceship is in braces

Yeah, you're absolutely correct. I jumped the gun on this one when seeing "{?}" in the output for the first time.

> P.S.: `std::strong_ordering` will be one of the type's stringifiable in the v2.5 stl stringification extension header ;)

This is in fact what I'm after. Until then I shall provide my own `operator<<` as needed. Thanks!
