### ISSUE TITLE
The tutorial example does not work (linker errors) with clang 10

### ISSUE THREAD

**Issue by sixcy** [doctest/doctest#637]
## Description

I cannot get the tutorial example of https://github.com/doctest/doctest/blob/master/doc/markdown/tutorial.md to compile.
Am I doing something wrong? Or is this a bug?
Thanks

### Steps to reproduce
Create factorial.cpp:
```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

int factorial(int number) { return number <= 1 ? number : factorial(number - 1) * number; }

TEST_CASE("testing the factorial function") {
    CHECK(factorial(1) == 1);
    CHECK(factorial(2) == 2);
    CHECK(factorial(3) == 6);
    CHECK(factorial(10) == 3628800);
}
```

Run the following command:
```
clang factorial.cpp -o factorial -Idoctest
```

Then I get a bunch of linker errors: https://pastebin.com/0xULZU4G

### Extra information
* doctest version: **v2.4.8**
* Operating System: **Ubuntu 20.04.4 LTS**
* Compiler+version: **clang 10.0.0-4ubuntu1, x86_64-pc-linux-gnu target**

**Comment by sixcy** [comment]
My bad, I was using clang instead of clang++ ;)

**Comment by onqtam** [comment]
can you compile a normal C++ hello world using `<iostream>`? Doesn't seem doctest related - maybe you need to use `clang++` instead of `clang` or something like that...

**Comment by onqtam** [comment]
oh, nvm :)

**Comment by sixcy** [comment]
> can you compile a normal C++ hello world using `<iostream>`? Doesn't seem doctest related - maybe you need to use `clang++` instead of `clang` or something like that...

Yes, indeed!
