### ISSUE TITLE
Doctest and PlatformIO: ERROR: test case THREW exception: unknown exception

### ISSUE THREAD

**Issue by Di3mex** [doctest/doctest#649]
## Description

I started using Doctest as soon as support for it became available in Platformio. So I am not sure if the issue is with doctest or PlatformIO, as I have not used doctest before. https://github.com/platformio/platformio-core/issues/4261#issue-1235509366

Basically what I am seeing is that exceptions/errors are not being printed. This makes troubleshooting tests, especially tests relying heavily on mocking frameworks time-consuming. 

```
Mock<HWInterface> mockHw;
When(Method(mockHw, milliseconds)).AlwaysReturn(1000);
```

Take for example this code using FakeIt to mock out the embedded hardware. Simply changing `AlwaysReturn` to just `Return` will fail the test whenever the mocked out method is called more than once. What the message would be, I actually don't know, because all I ever get when something goes wrong is: 

`"ERROR: test case THREW exception: unknown exception"`

### Steps to reproduce
```
#define DOCTEST_CONFIG_IMPLEMENT // REQUIRED: Enable custom main()
#include <doctest.h>

struct my_little_exception {};

TEST_CASE("I'll just throw something") {
    SUBCASE("I hope someone is going to catch it") {
        throw my_little_exception();
    }
}

int main(int argc, char **argv) {
    doctest::Context context;

    // BEGIN:: PLATFORMIO REQUIRED OPTIONS
    context.setOption("success", true);     // Report successful tests
    context.setOption("no-exitcode", true); // Do not return non-zero code on failed test case
    // END:: PLATFORMIO REQUIRED OPTIONS

    // YOUR CUSTOM DOCTEST OPTIONS

    context.applyCommandLine(argc, argv);
    return context.run();
}
```

#### PlatformIO build/compiler options

```
[env:native]
platform = native
build_type = debug
debug_test = test_native
debug_build_flags = -O0 -g3 -ggdb3
test_framework = doctest
build_flags = 
  -O0
  -Wall 
  -D DOCTEST_CONFIG_NO_POSIX_SIGNALS
```

### Extra information

* doctest version: **v2.4.8**
* Operating System: **Windows 10 64 Bit**
* Compiler+version: **gcc (GCC) 11.2.0** (via cygwin)

**Comment by Saalvage** [comment]
Does [this](https://github.com/doctest/doctest/blob/master/doc/markdown/stringification.md#translating-exceptions) maybe help?

**Comment by FranckRJ** [comment]
It's because FakeIt throws exceptions that don't inherit from std::exception by default. Since version 2.3.0 there is doctest integration that you can use that will print a real error message explaining the issue.

**Comment by Saalvage** [comment]
Thank you very much for your insights FranckRJ!

I am closing this under the assumption that this is a satisfying resolution. If there's anything else please feel free to reopen/open a new issue!
