### ISSUE TITLE
Deadlock in MpiConsoleReporter when root rank fails assert

### ISSUE THREAD

**Issue by starintheuniverse** [doctest/doctest#655]
## Description
Thanks for a great library and especially for an MPI extension! I am developing an MPI-based scientific library, so the MPI extension is critical for my usage of doctest.

For me all of the following MPI_TEST_CASE deadlock (with mpirun -np 2):

```
#include <doctest/extensions/doctest_mpi.h>
```

```
MPI_TEST_CASE("Root fails",1) {
  CHECK( 1 == 0 );
}
```
```
MPI_TEST_CASE("Root fails",2) {
  CHECK( 1 == 0 );
}
```
```
MPI_TEST_CASE("Root fails",2) {
  CHECK( test_rank != 0 );
}
```

This seems related to a note from the initial version (#418, [extensions.md](https://github.com/BerengerBerthoul/doctest/blob/339ec122bece7c45bd2892ea4701e0b6f491fb59/doc/markdown/extensions.md)):
> If the number of processes is not enought, prints the correct message, but then deadlocks (comes from MPI_Probe in MpiConsoleReporter)

Although #611 fixed deadlock for an insufficient process count (by eliminating a code path that fails a CHECK), there remains an underlying communication bug.

### Extra information
* doctest version: **v2.4.8** (dev at 16ed548bc9)
* Operating System: **Linux Mint 20 Cinnamon 4.6.7**
* Compiler+version: **gcc 9.3.0**
* MPI standard: **MPI-3.1**
* MPI implementation: **MPICH 3.3.2**

### Problem code

`doctest/extensions/mpi_reporter.h`

I think the deadlock comes from a technical dependency of MPI_Send in `log_assert()` upon the matching MPI_Recv in `test_case_end()`, which is not called until after `log_assert()`.

This is a 'may' dependency. [MPI Standard 3.1, section 3.4](https://www.mpi-forum.org/docs/mpi-3.1/mpi31-report/node57.htm#Node57):
> The standard mode send is _non-local_: successful completion of the send operation may depend on the occurrence of a matching receive.

Probably this bug has escaped notice due to the indefinite nature of the dependency. If the MPI implementation decides to buffer the message of MPI_Send, then deadlock is avoided. In my case, when rank 0 sends to itself, it would appear that the MPI implementation instead has a policy of blocking for the matching receive (to avoid an extra copy perhaps) leading to deadlock. As per the standard, however, we cannot make any assumption about when a standard mode MPI_Send will depend on its matching MPI_Recv or not.

### Proposed solution

I believe this bug would be fixed by splitting MPI_Send into MPI_Isend / MPI_Waitall enclosing the loop of MPI_Recv. That means moving the sends from `log_assert()` into `test_case_end()`.

To do that will require storing the messages in the meantime. (Effectively, handling the buffering ourselves.) For simplicity, I would store the messages in a `std::vector<std::string>` new member of MpiConsoleReporter that gets flushed on every `test_case_end()`.

I will plan to implement this solution in a PR in the next couple of days. Would also love to hear any comments, especially from @BerengerBerthoul and @philbucher .

**Comment by BerengerBerthoul** [comment]
Hi,
Thanks for the detailed description and PR #656 !
I tested it on our unit test suites and I see no regression on my side.
