### ISSUE TITLE
MESSAGE in lambda outputs CHECK_MESSAGE's message even if it's not failure.

### ISSUE THREAD

**Issue by Dicklessgreat** [doctest/doctest#658]
### Steps to reproduce

```
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "https://raw.githubusercontent.com/onqtam/doctest/dev/doctest/doctest.h"
#include <functional>

TEST_CASE("Strange behavior")
{
    CHECK_MESSAGE([]() {
        MESSAGE("message!!");
        return true;
        }(), 
        "lambda Failed!!");
}
```
This outputs...
```
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
===============================================================================
<source>:5:
TEST CASE:  Strange behavior

<source>:8: MESSAGE: message!!
  logged: lambda Failed!!

===============================================================================
[doctest] test cases: 1 | 1 passed | 0 failed | 0 skipped
[doctest] assertions: 1 | 1 passed | 0 failed |
[doctest] Status: SUCCESS!
```
https://godbolt.org/z/z1aqdjj1h

I expected it outputs like that...
```
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
===============================================================================
<source>:5:
TEST CASE:  Strange behavior

<source>:8: MESSAGE: message!!
===============================================================================
[doctest] test cases: 1 | 1 passed | 0 failed | 0 skipped
[doctest] assertions: 1 | 1 passed | 0 failed |
[doctest] Status: SUCCESS!
```
### Extra information

* doctest version: **v2.4.8**
* Operating System: **(godbolt)**
* Compiler+version: **MSVC, Clang, GCC...latest**

### Why this matters?
I'm using libraries with monad interfaces in my code, like [tl::optional](https://github.com/TartanLlama/optional) or [tl::expected](https://github.com/TartanLlama/expected).
I sometimes make unit test like...
```
tl::optional<MyData> funcToTest();

TEST_CASE("MyData test")
{
    CHECK_MESSAGE(funcToTest().map(
    [&](MyData data)
    {
        ProcessData(data);
        Message(data.toString());
    }).has_value(),
    "funcToTest() failed");
}
```
thanks.

**Comment by Saalvage** [comment]
I very much think this is by design. Why this design was chosen I cannot say. Maybe @onqtam has some insight?

**Comment by onqtam** [comment]
Seems to be by design - `CHECK_MESSAGE` is basically a `do { INFO(...); CHECK(...); } while(false);` and the `MESSAGE()` in the lambda in the `CHECK()` triggers the printing of all previous `INFO()` calls.

**Comment by Dicklessgreat** [comment]
Got it.
So, what is the current best way to handle messages in the monad?

A simple thing that comes to my mind quickly is,
```
tl::optional<MyData> funcToTest();

TEST_CASE("MyData test")
{
    std::string msg;
    CHECK_MESSAGE(funcToTest().map(
    [&](MyData data)
    {
        ProcessData(data);
        msg += data.toString();
    }).has_value(),
    "funcToTest() failed");
    if (! msg.empty())
        MESSAGE(msg);
}
```
A little messy...but if it's by design, there is no choice but to do so.

**Comment by onqtam** [comment]
I suppose that's one way to do it - haven't given it much thought. Also, isn't the `"funcToTest() failed"` message redundant since whatever is in the `CHECK()` will be stringified & outputted?

**Comment by onqtam** [comment]
https://github.com/doctest/doctest/blob/dev/doc/markdown/configuration.md#doctest_config_asserts_return_values

**Comment by Dicklessgreat** [comment]
> Also, isn't the `"funcToTest() failed"` message redundant since whatever is in the `CHECK()` will be stringified & outputted?

Yes, you're right. sorry for the bad example. It's only a simplified one.
What I wanted to describe was `CHECK_MESSAGE` prints out failed message.

> Btw another way to do it would be to put the CHECK() in an if() and then have the MESSAGE() in the then part but for that you'd need to define DOCTEST_CONFIG_ASSERTS_RETURN_VALUES:

That seems useful for me! Thanks for your suggestion.

**Comment by Saalvage** [comment]
I would like to keep this open to potentially address it in the future. I feel like `MESSAGE` should not trigger previous `INFO` invocations. But it definitely requires some more thought.

**Comment by onqtam** [comment]
The original reasoning was that just like there are 3 levels of severity for assertions (warn/check/require), there are 3 levels of severety for such messages (message/fail_check/fail)

**Comment by onqtam** [comment]
The original reasoning was that just like there are 3 levels of severity for assertions (`warn`/`check`/`require`), there are 3 levels of severity for messages (`message`/`fail_check`/`fail`).

If an actual failure like with `fail_check` or `fail` happens we should see everything logged with `INFO` prior to that, but indeed the case for doing the same with `message` is weaker.
