### ISSUE TITLE
Visual Studio's Test Explorer and Resharper C++'s Unit Test Explorer don't see Doctest's tests

### ISSUE THREAD

**Issue by KulaGGin** [doctest/doctest#661]
## Description

I created a solution in Visual Studio with a command line project. I then downloaded the doctest header from the releases and placed it in the project folder. I then added the header to the project. I then pasted the code from the tutorial into the .cpp file.

When I open Visual Studio's Test Explorer view or Resharper C++'s Unit Test Explorer view, they fail to identify any tests:
![devenv_zRMbOBBEeh](https://user-images.githubusercontent.com/16989713/173700649-c9d32d0d-610d-4d6e-a8b8-e92ead504179.png)

When I run the executable from the command line, it works:
![cmd_slE6FGMi6b](https://user-images.githubusercontent.com/16989713/173700703-91d4ce91-dff0-4a72-98b3-6325de69c2fa.png)

I'd expect for at least Resharper C++ to recognize the doctest, since the framework is featured on their website.

### Extra information
* doctest version: **v2.4.8**
* Operating System: **Windows 10 x64**
* Visual Studio: 2022 (64-bit) - Current Version 17.0.0
* ReSharper: 2021.3.1 Build 213.0.20211208.204613

**Comment by KulaGGin** [comment]
As Salvage suggested on Discord, I tried v2.4.7 and it still didn't work. Then I tried v.2.4.6 and Resharper saw the test:
![devenv_nGFTcOM2o9](https://user-images.githubusercontent.com/16989713/173815736-0fbc8ab2-977d-4d6c-91c3-6713306fe535.png)

**Comment by igor-akhmetov** [comment]
Hello @KulaGGin,
You need to update to ReSharper 2022.1, which includes support for the recent doctest releases.
