### ISSUE TITLE
Since doctest 2.4.8, some macros create a lambda. This prevents testing coroutine-stuff

### ISSUE THREAD

**Issue by andreasbuhr** [doctest/doctest#662]
Hi, I am maintaining a fork of Lewis Baker's cppcoro at https://github.com/andreasbuhr/cppcoro. I wanted to update doctest to the latest version 2.4.8. Unfortunately, this is not possible. 

Since this commit, it is not possible any more to test anything containing a co_* statement:
https://github.com/doctest/doctest/commit/e84f16e943fb7677a449e4e234b228d9188dd7ba

This commit introduced lambdas. So there mustn't be any co_await, co_yield or similar inside. This breaks all tests like this here:
https://github.com/andreasbuhr/cppcoro/blob/167571d68652d376b25378b3bb9c77f62c812136/test/async_generator_tests.cpp#L63

It would be great if you could move away from the lambdas again, so coroutine-stuff can be tested again.

Steps to reproduce if you are using gcc:
```
git clone https://github.com/andreasbuhr/cppcoro
cd cppcoro
git checkout update_doctest_248
mkdir build
cd build
cmake -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug ..
cmake --build . 
```
If you are using clang, use
```
cmake -GNinja -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=-stdlib=libc++ -DCMAKE_EXE_LINKER_FLAGS=-lc++ ..
```

**Comment by Saalvage** [comment]
This breaking change is being reverted in 2.4.9. For more details see #636.
I'm very sorry for the inconvenience! I am actually working on getting 2.4.9 out of the door today.

**Comment by andreasbuhr** [comment]
Hi @Saalvage, thanks a lot for this very quick response. I already integrated doctest 2.4.9 into the main branch of cppcoro. Thanks a lot for your work.
