### ISSUE TITLE
Update Doctest in vcpkg to 2.4.9

### ISSUE THREAD

**Issue by Tradias** [doctest/doctest#663]
With the shiny 2.4.9 release, let's update the doctest port in vcpkg as well.

I should be able to do that.

**Comment by Saalvage** [comment]
I was just looking into doing just that!
However, I've never touched vcpkg, so assuming you have, you're probably the better fit for the job.
Thank you!

**Comment by Tradias** [comment]
Doctest creates a doctest.h file using assemble_single_header.cmake in the source directory. That is a no-go in vcpkg, the source directory should not be modified (to allow parallel CMake configure runs). It can be circumvented by setting `DISABLE_PARALLEL_CONFIGURE` in https://vcpkg.readthedocs.io/en/latest/maintainers/ports/vcpkg-cmake/vcpkg_cmake_configure/ but ideally should be fixed upstream.

I will submit it to vcpkg as is with the disabled parallel-configure, let's see what they will say.

**Comment by Tradias** [comment]
Our company internal dependency manager also doesn't like modifications of the source directory, so it would be cool to have an option to avoid that.

**Comment by Saalvage** [comment]
Hmm are you sure that is relevant here?
`assemble_single_header` seems to only be added as a target when doctest is built as the main project.
https://github.com/doctest/doctest/blob/b7c21ec5ceeadb4951b00396fc1e4642dd347e5f/CMakeLists.txt#L35-L51
https://github.com/doctest/doctest/blob/b7c21ec5ceeadb4951b00396fc1e4642dd347e5f/CMakeLists.txt#L14-L18
Which I assume is neither the case for vcpkg, nor your company's internal dependency manager?

Either way, this is not a recent change, so it should be fine by vcpkg if they haven't complained this far.

**Comment by Tradias** [comment]
I think most package managers including vcpkg and our internal one first clone the source code and then run normal cmake configure + install on it, which means doctest will be the MAIN_PROJECT.

Vcpkg didn't complain because the doctest port was using some outdated stuff. I have updated it, but you are probably right, they will be ok with it.

**Comment by Saalvage** [comment]
I will look into it.

Could you please update the link from onqtam/doctest to doctest/doctest while you're at it?

**Comment by Tradias** [comment]
Done
