### ISSUE TITLE
doctest 2.4.9: Pointer comparison in MSVC

### ISSUE THREAD

**Issue by nickdademo** [doctest/doctest#665]
## Description
From doctest 2.4.8. to 2.4.9, there seems to be a change in the way pointers are compared. Trivial example below:

```
    DOCTEST_TEST_CASE("object equality test")
    {
        const auto a = new int();
        const auto b = a;

        //DOCTEST_CHECK(a == b); // compile error
        DOCTEST_CHECK((a == b)); // OK
    }
```

```
error LNK2019: unresolved external symbol "public: static void __cdecl doctest::detail::filldata<void const *>::fill(class std::basic_ostream<char,struct std::char_traits<char> > *,void const *)" (?fill@?$filldata@PEBX@detail@doctest@@SAXPEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@PEBX@Z) referenced in function "public: struct doctest::detail::Result __cdecl doctest::detail::Expression_lhs<int * const &>::operator==<int * const &>(int * const &)" (??$?8AEBQEAH@?$Expression_lhs@AEBQEAH@detail@doctest@@QEAA?AUResult@12@AEBQEAH@Z)
```

Looks like doctest is treating the pointers as strings?

Is this an expected new change?

### Steps to reproduce
Run the attached minimal example (configure with CMake).

### Extra information
* doctest version: **v2.4.9**
* Operating System: **W10**
* Compiler+version: **VS 2022 17.2.4**

[doctest-bug.zip](https://github.com/doctest/doctest/files/9132323/doctest-bug.zip)

**Comment by Saalvage** [comment]
Fixed in dev!

**Comment by dankamongmen** [comment]
when can we get a release of this? it's kept notcurses from building for some time =\. i'm holding fedora back from 2.4.9 in the hope we get a release soon.
