### ISSUE TITLE
Cannot define custom `my_namespace::toString(const T& t)` without return type conflicts

### ISSUE THREAD

**Issue by ChrisThrasher** [doctest/doctest#666]
## Description
[SFML](https://github.com/SFML/SFML.git) would like to define text conversion free functions for various types. These all reside within SFML's `sf::` namespace and given the stylistic conventions of the library and our API preferences would be declared as such
```cpp
std::string sf::toString(const T& t);
```
Overloads of `operator<<(std::ostream&, const T& t)` also exist for all these types. However, when trying to build our test executables, doctest.h is attempting to compile these `toString` overloads via ADL but because they return `std::string` instead of `doctest::String`, compilation fails.

My expectation was that because `operator<<` exists, that would get called instead of `toString`. Is there any way to define a `toString` overload with different returns types without compilation failure?

### Steps to reproduce
Define custom `toString(const T& T)` overload with a return type which is not compatible with doctest::String. Observe doctest.h fail to compile.

### Extra information
* doctest version: **v2.4.9**
* Operating System: **macOS 12**
* Compiler+version: **AppleClang 13.1.6**

**Comment by Saalvage** [comment]
Does [this](https://github.com/doctest/doctest/blob/master/doc/markdown/configuration.md#doctest_config_double_stringify) solve your issue?

**Comment by ChrisThrasher** [comment]
Unfortunately not. I don't even see any references to `DOCTEST_CONFIG_DOUBLE_STRINGIFY` in the copy of doctest.h I got from the latest release.

**Comment by Saalvage** [comment]
No worries! That option was introduced in 2.4.9 to address this exact issue. :)
