### ISSUE TITLE
Linking issue with static members

### ISSUE THREAD

**Issue by alcontre** [doctest/doctest#668]
## Description
It seems as if referencing a static data member within a `REQUIRE()` macro causes some issues. 

### Steps to reproduce
Example:

```c++
#include DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include <cstdint>

struct Foo {
   static constexpr std::uint32_t foo = 23;
};

TEST_CASE("a") {
   REQUIRE(23 == Foo::foo); // Fails to link
}
TEST_CASE("b") {
   static constexpr auto expected = Foo::foo;
   REQUIRE(23 == expected); // ok
}

static constexpr auto expected2 = Foo::foo;
TEST_CASE("c") {
   REQUIRE(23 == expected2); // ok
}
```
### Extra information
* doctest version: v2.4.9
* Operating System: CentOS 7
* Compiler+version: gcc 9.3.1 (Redhat devtoolset-9) and clang 9.0.1 (Redhat llvm-toolset-9.0)

**Comment by onqtam** [comment]
The assert macros ODR-use whatever is passed to them and that is problematic with such static constants - you can try defining [`DOCTEST_CONFIG_ASSERTION_PARAMETERS_BY_VALUE`](https://github.com/doctest/doctest/blob/master/doc/markdown/configuration.md#doctest_config_assertion_parameters_by_value) before including the header in a translation unit to avoid the problem. Let us know if this helps!

**Comment by alcontre** [comment]
Ahh, I see that now. Thank you!

**Comment by Saalvage** [comment]
I presume this to be fixed? If there are more questions feel free to reopen!
