### ISSUE TITLE
doctest 2.4.9: function pointer comparison does not compile any more

### ISSUE THREAD

**Issue by ascii255** [doctest/doctest#675]
## Description
Since version 2.4.9 function pointers seem to be compared differently. If you compile the following example, you will get the error

```
/usr/local/include/doctest/doctest.h:1166:49: Cannot initialize a parameter of type 'const void *' with an lvalue of type 'void (*)()'
```

This seems to be similar as https://github.com/doctest/doctest/issues/665#issue-1279903353

### Steps to reproduce
```
void function() {}

DOCTEST_TEST_CASE("function pointer equality test")
{
    void (*function_pointer)() = &function;
    
    DOCTEST_CHECK(function_pointer == &function); // compile error
}
```

### Extra information
* doctest version: **v2.4.9**
* Operating System: **OSX**
* Compiler+version: **Apple clang version 13.1.6 (clang-1316.0.21.2.5)**

**Comment by Saalvage** [comment]
Fixed in dev!
