### ISSUE TITLE
What is the 'throw_if' 

### ISSUE THREAD

**Issue by Viiic** [doctest/doctest#714]
## Description
I'm wondering what does 'throw_if' do in the [assertion_macros](assertion_macros.cpp) sample. There are bunch of 'throw_if' used in the examples. However, I cannot find anything about it except the new function in Laravel, but they are probably the same one.

**Comment by Saalvage** [comment]
`throw_if` simply throws its second argument when the first argument evaluates to true:
https://github.com/doctest/doctest/blob/86892fc480f80fb57d9a3926cb506c0e974489d8/examples/all_features/header.h#L5-L15

**Comment by onqtam** [comment]
it's basically a utility function for easier testing of doctest itself

**Comment by Viiic** [comment]
Thank you!
