### ISSUE TITLE
Better CHECK_THROWS

### ISSUE THREAD

**Issue by mingmoe** [doctest/doctest#716]
The `CHECK_THROWS` macro isn't so easy to use.

See:
```c++
TEST_CASE("Test") {
    CHECK_THROWS(
        [&]
        {
         throw 1;   
        });
}
```
This not work. Won't throw any exception.

But this work.
```c++
TEST_CASE("Test") {
    CHECK_THROWS(
        [&]
        {
         throw 1;   
       // added ()
        }());
}
```

Any solutions? Or add this to FAQ

**Comment by Saalvage** [comment]
Judging from this issue it might seem a bit unintuitive, but you can simply do `CHECK_THROWS(throw 1);`

**Comment by mingmoe** [comment]
Both the two codes can be compiled and execute. 

But the first one won't really call the lambda.(I haven't saw any warnings)

This may be confusing for the new.

Examples only have the form as `CHECK_THROWS_WITH(func(),xxxx)`. 

No `CHECK_THROWS_WITH(throw 1,xxxx);` or others to show more usage.

What about add this example to the document(or FAQ)? Or a better way?

**Comment by Saalvage** [comment]
Added clarifying documentation in #717! 👍
