### ISSUE TITLE
get error alignment in CHECK macro

### ISSUE THREAD

**Issue by PikachuHyA** [doctest/doctest#723]
## Description

The struct `dummy_4` is defined in both `a.cpp` and `b.cpp` with different `alignment requirement`.

In file `b.cpp` TEST_CASE, error alignment got in CHECK macro.
```
CHECK(alignof(dummy_4) == std::alignment_of_v<dummy_4>);
```

see https://en.cppreference.com/w/cpp/types/alignment_of and https://en.cppreference.com/w/cpp/language/alignof .

### Steps to reproduce

a simple project in my GitHub repo: https://github.com/PikachuHyA/doctest_demo

file a.cpp
```
#include <type_traits>

#include "doctest.h"

using namespace doctest;

struct alignas(4) dummy_4 {
  char a;
  short b;
};

TEST_CASE("test in file a") {
  // If we remove this check statement,
  // "test in file b" will pass
  // Why?
  CHECK(std::alignment_of_v<dummy_4> == 4);
}
```
file b.cpp
```
#include <type_traits>

#include "doctest.h"

using namespace doctest;

#pragma pack(push, 4)
struct dummy_4 {
  char a;
  short b;
};
#pragma pack(pop)
TEST_CASE("test in file b") {
  // check fail
  // maybe bug?
  CHECK(alignof(dummy_4) == std::alignment_of_v<dummy_4>);
  // However, static_assert passed
  static_assert(alignof(dummy_4) == std::alignment_of_v<dummy_4>);
}

```

run log

```
[doctest] doctest version is "2.4.9"
[doctest] run with "--help" for options
===============================================================================
/Users/shuoshu/CLionProjects/doctest_demo/b.cpp:13:
TEST CASE:  test in file b

/Users/shuoshu/CLionProjects/doctest_demo/b.cpp:16: ERROR: CHECK( alignof(dummy_4) == std::alignment_of_v<dummy_4> ) is NOT correct!
  values: CHECK( 2 == 4 )

===============================================================================
[doctest] test cases: 2 | 1 passed | 1 failed | 0 skipped
[doctest] assertions: 2 | 1 passed | 1 failed |
[doctest] Status: FAILURE!
```

### Extra information

* doctest version: **v2.4.9** (the latest main branch)
* Operating System: **macOS Monterey 12.6**
* Compiler+version: **clang version 14.0.6**

**Comment by onqtam** [comment]
This is a violation of the ODR (one definition rule) rule - the compiler removes one of the 2 definitions of the struct as they are named the same and have the same linker visibility. This is not doctest-related - if instead of test cases you had normal functions with if statements in the 2 different .cpp files you'd get the same result.

**Comment by cschreib** [comment]
You are providing two different definitions of `dummy_4` in the global namespace in `a.cpp` and `b.cpp`, which breaks the one-definition-rule. I believe this is causing undefined behavior, which explains the nonsensical results you are seeing.

To avoid breaking the one-definition-rule, you need to put the definition of `dummy_4` inside an anonymous namespace, like so:
```c++
namespace {
    struct dummy_4 {
        // ...
    };
}
```

If you do this in both `a.cpp` and `b.cpp`, your tests pass.

**Comment by Saalvage** [comment]
So I'm going to close this as it doesn't seem like it's an issue with doctest, if there's anything else feel free to reopen/open another issue!

Thank you very much for looking into this cschreib!
