### ISSUE TITLE
Consider re-running the benchmarks

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#729]
The benchmark page:

https://github.com/doctest/doctest/blob/master/doc/markdown/benchmarks.md

is by now 3 years old, perhaps more. Please consider re-running the same benchmarks (with the relevant newer versions of compilers and of catch etc.) and changing the values accordingly.

**Comment by onqtam** [comment]
My guess: doctest has become 10-20% slower due to features & includes, Catch has become 20-30% faster since it's no longer single header and has moved some includes out of the interface part. But the bench should definitely be redone at some point!

**Comment by onqtam** [comment]
there's a new entrant in the fast testing library space: https://github.com/cschreib/snitch

**Comment by cdeln** [comment]
Duplicate of https://github.com/doctest/doctest/issues/586

**Comment by eyalroz** [comment]
True.
