### ISSUE TITLE
Compile error with tag 1.2.9 (C++98 compliant)

### ISSUE THREAD

**Issue by araggohnxd** [doctest/doctest#739]
## Description

I'm currently trying to use `doctest` in the C++98 standard, therefore I downloaded the release from 1.2.9 tag, as suggested by the documentation. The problem is, I can't compile it, cause it gives me this error:
```
In file included from doctest_main.cpp:2:
doctest.h:4408:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4408 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
```

Before anyone asks, it is a school project, I'm forced to use C++98, please don't recommend getting a more recent version unless it is compliant with the standard.

### Steps to reproduce

Simply get the header and try to compile code including it.

### Extra information

* doctest version: **v1.2.9**
* Operating System: **WSL running Arch Linux**
* Compiler+version: **c++ (GCC) 12.2.1 20230111**

**Comment by onqtam** [comment]
try defining [`DOCTEST_CONFIG_NO_POSIX_SIGNALS`](https://github.com/doctest/doctest/blob/master/doc/markdown/configuration.md#doctest_config_no_posix_signals) before including the header

**Comment by araggohnxd** [comment]
It works. Thank you very much!
