### ISSUE TITLE
[Feature] Provide a pkgconfig .pc file

### ISSUE THREAD

**Issue by inglor** [doctest/doctest#742]
## Description
Please provide a pkgconfig spec file with the install target.

### Steps to reproduce
Compile and install and observe there's no pkgconfig file. Usually this goes to `/usr/lib/pkgconfig/doctest.pc`

### Extra information

* doctest version: **v2.4.9**
* Operating System: **Linux**
* Compiler+version: **gcc**

**Comment by cdeln** [comment]
This has been suggested her as well: https://github.com/doctest/doctest/issues/850 . I will close this as a duplicate since I started a discussion in the other thread, feel free to join the discussion and make a contribution if you like.
