### ISSUE TITLE
2.4.11 no longer builds: `error: expected ‘>’ before ‘*=’ token`

### ISSUE THREAD

**Issue by a-cristi** [doctest/doctest#759]
## Description

Using the `doctest.h` file from the [2.4.11 release page](https://github.com/doctest/doctest/releases/tag/v2.4.11) I am no longer able to compile a simple example.

### Steps to reproduce

```c++
#include "doctest.h"
```

Compilation fails with:

```text
doctest.h:1587:130: error: expected ‘>’ before ‘*=’ token
 1587 |             template <typename L, typename types::enable_if<!doctest::detail::types::is_rvalue_reference<L>::value, void >::type *= nullptr>
```

### Extra information

* doctest version: **2.4.11**
* Operating System: **Ubuntu 22.04.2** and **Windows**
* Compiler+version: **g++ 11.3.0**, **clang++ 14.0.0-1ubuntu1**, **MSVC 19.29.30147**

**Comment by onqtam** [comment]
which version were you using before that?

**Comment by onqtam** [comment]
weird - all builds are passing: https://github.com/doctest/doctest/actions/runs/4426380692

there should be something special about your setup

**Comment by a-cristi** [comment]
I think you're right. Re-downloading [the same doctest.h](https://github.com/doctest/doctest/releases/tag/v2.4.11) and diffing it against the file that gives me troubles shows some weird differences, so I must have corrupted it somehow the first time. Sorry for the troubles.
