### ISSUE TITLE
Example video: `fact(0) == 1` most definitely shouldn't fail, actually ;)

### ISSUE THREAD

**Issue by xparq** [doctest/doctest#760]
I mean, it says `fact()` is meant to be the factorial function, not just a test of some random fact. :)

(Cheers anyway, first-time visitor here, just lingering yet...)

**Comment by Saalvage** [comment]
"Should fail" is just meant to indicate that the implementation for this test case is erroneous, not that fact(0) isn't actually 1. ;P

**Comment by xparq** [comment]
Fair enough! :)
