### ISSUE TITLE
clang-tidy warnings when using SUBCASE

### ISSUE THREAD

**Issue by bilderbuchi** [doctest/doctest#761]
I am seeing unexpected warnings from clang-tidy in my test code. It seems to boil down to variables being used in nested macros `TEST_CASE` and `SUBCASE`

For example, inside a `TEST_CASE`, I declare `int myint;`, define myint inside a `SUBCASE`, and then use it later on in the `TEST_CASE` body, I get e.g. `warning: 1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]`.

Is that a known issue, or am I having unreasonable expectations? I could not find anything in the issue tracker.

I'm using doctest 2.4.10 and clang-tidy 15.0.7

I managed to get a reproducer: 
```cpp
// Compile with g++ myprogram.cpp
// Check with clang-tidy myprogram.cpp --config="" --
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

int factorial(int number) { return number <= 1 ? number : factorial(number - 1) * number; }

TEST_CASE("1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]")
{
   int input;
   int output;

   SUBCASE("Scenario A")
   {
      input  = 3;
      output = 6;
   }
   // more SUBCASEs here in reality, setting up different combinations of inputs and outputs...
   // this line gives warning: 1st function call argument is an uninitialized value [clang-analyzer-core.CallAndMessage]
   CHECK(factorial(input) == output);
}
```

_Originally posted by @bilderbuchi in https://github.com/doctest/doctest/discussions/748#discussioncomment-5343387_

**Comment by JWleo** [comment]
Clang tidy supports a wide variety of checks. Many of them are to a few degree based on opinion. Not all of them apply to every project. 
if you think it's not reasonable to warn, so f**k  it and delete this fool warning of opinion in clang-tidy

**Comment by bilderbuchi** [comment]
You're surely entitled to your opinion (and I agree with you that clang-tidy has some warnings that can be regarded opinion-like), but personally appreciate it if clang-tidy warns me if I am using an uninitialized value, so I don't consider this a "fool warning" nor "opinion". 
In this case the warning comes from even "deeper", the [clang static analyzer](https://clang.llvm.org/docs/ClangStaticAnalyzer.html), not clang-tidy itself.

The questions here are more if doctest is doing some shenanigans with macros that should be avoided (i.e. they are a real potential issue that should be flagged), or if doctest uses some macro usage pattern that the clang static analyzer does not (yet) recognize, and if said pattern can be avoided (and/or an issue filed upstream).

**Comment by cdeln** [comment]
@bilderbuchi Well, you don't initialize your variables. Not a doctest bug, you should initialize your variables, that is what clang complains about.

BTW, no need to use clang-tidy to repro this, just use clang with `-Wall` flag and you will get a massive warning.

I suggest we close as not a bug.

**Comment by bilderbuchi** [comment]
> Well, you don't initialize your variables. Not a doctest bug, you should initialize your variables, that is what clang complains about.

But I *do* initialize them before use -- inside `SUBCASE`?

**Comment by cdeln** [comment]
The doctest macros add layers of indirection. One can't assume that the compiler will investigate all code paths to arbitrary level of depth. The compiler warns about **potentially** uninitialized values, it doesn't say they are for sure.

**Comment by bilderbuchi** [comment]
> The compiler warns about potentially uninitialized values, it doesn't say they are for sure.

I see " 1st function call argument **is an uninitialized value**" -- I can't read any "potentially" in that message? 

I think I originally suspected that in the macro expansion somehow code paths are generated where the SUBCASE is left out (in which case the compiler is right to warn) and the SUBCASE branch is handled in another place. That, i.e. having a testcase without subcase, does not make sense and would maybe be elided later? I have no clue about doctest internals, so I did not speculate at the time.

**Comment by cdeln** [comment]
I compile the following code with `clang++ -Wall` (Ubuntu clang version 16.0.6)

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

int factorial(int number) { return number <= 1 ? number : factorial(number - 1) * number; }

TEST_CASE("761")
{
   int input;
   int output;

   SUBCASE("Scenario A")
   {
      input  = 3;
      output = 6;
   }
   CHECK(factorial(input) == output);
}
```
which gives me
```console
main.cpp:11:4: warning: variable 'input' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
   SUBCASE("Scenario A")
   ^~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:2945:23: note: expanded from macro 'SUBCASE'
#define SUBCASE(name) DOCTEST_SUBCASE(name)
                      ^~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:2279:41: note: expanded from macro 'DOCTEST_SUBCASE'
    if(const doctest::detail::Subcase & DOCTEST_ANONYMOUS(DOCTEST_ANON_SUBCASE_) DOCTEST_UNUSED =  \
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:422:30: note: expanded from macro 'DOCTEST_ANONYMOUS'
#define DOCTEST_ANONYMOUS(x) DOCTEST_CAT(x, __COUNTER__)
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:420:29: note: expanded from macro 'DOCTEST_CAT'
#define DOCTEST_CAT(s1, s2) DOCTEST_CAT_IMPL(s1, s2)
                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:419:34: note: expanded from macro 'DOCTEST_CAT_IMPL'
#define DOCTEST_CAT_IMPL(s1, s2) s1##s2
                                 ^~~~~~
<scratch space>:216:1: note: expanded from here
DOCTEST_ANON_SUBCASE_16
^~~~~~~~~~~~~~~~~~~~~~~
main.cpp:16:20: note: uninitialized use occurs here
   CHECK(factorial(input) == output);
                   ^~~~~
/usr/include/doctest/doctest.h:2969:34: note: expanded from macro 'CHECK'
#define CHECK(...) DOCTEST_CHECK(__VA_ARGS__)
                                 ^~~~~~~~~~~
/usr/include/doctest/doctest.h:2440:65: note: expanded from macro 'DOCTEST_CHECK'
#define DOCTEST_CHECK(...) DOCTEST_ASSERT_IMPLEMENT_1(DT_CHECK, __VA_ARGS__)
                                                                ^~~~~~~~~~~
/usr/include/doctest/doctest.h:2396:49: note: expanded from macro 'DOCTEST_ASSERT_IMPLEMENT_1'
        DOCTEST_ASSERT_IMPLEMENT_2(assert_type, __VA_ARGS__);                                      \
                                                ^~~~~~~~~~~
/usr/include/doctest/doctest.h:2390:16: note: expanded from macro 'DOCTEST_ASSERT_IMPLEMENT_2'
            << __VA_ARGS__)) /* NOLINTNEXTLINE(clang-analyzer-cplusplus.NewDeleteLeaks) */         \
               ^~~~~~~~~~~
/usr/include/doctest/doctest.h:2146:9: note: expanded from macro 'DOCTEST_WRAP_IN_TRY'
        x;                                                                                         \
        ^
main.cpp:11:4: note: remove the 'if' if its condition is always true
   SUBCASE("Scenario A")
   ^~~~~~~~~~~~~~~~~~~~~
/usr/include/doctest/doctest.h:2945:23: note: expanded from macro 'SUBCASE'
#define SUBCASE(name) DOCTEST_SUBCASE(name)
                      ^
/usr/include/doctest/doctest.h:2279:5: note: expanded from macro 'DOCTEST_SUBCASE'
    if(const doctest::detail::Subcase & DOCTEST_ANONYMOUS(DOCTEST_ANON_SUBCASE_) DOCTEST_UNUSED =  \
    ^
main.cpp:8:13: note: initialize the variable 'input' to silence this warning
   int input;
            ^
             = 0
1 warning generated.
```

Clang is unable to infer that that the code setting the variable is always executed. And you know what, it doesn't if you supply `--subcase-exclude="Scenario A"` to your test executable.

BTW, if you are interested to see what doctest macros expand to, compile your code with `-E` flag. It will give you almost 100K lines of code on stdout, so pipe that into a file and scroll to the bottom and you will see the code that the compiler actually sees after macro expansion.

**Comment by bilderbuchi** [comment]
> it doesn't if you supply `--subcase-exclude="Scenario A"`

Ha, of course. I did not know/consider that -- now it makes sense that execution can bypass the subcase!

> if you are interested to see what doctest macros expand to, compile your code with -E flag

Good tip, thanks!

I agree with closing.
