### ISSUE TITLE
How does one make a test setup method?

### ISSUE THREAD

**Issue by erik-whiting** [doctest/doctest#763]
Hello, this is actually just a question. I'm sorry if it's outlined in the docs but I couldn't find it.

Basically, how do I run a test setup method just once? For example:

```cpp
TEST_CASE("Test object side effects") {
    ObjectToTest ott(params_object);
    // Instantiating `ObjectToTest` has several side effects, let's make sure they all happened

    SUBCASE("Creates a file") {
        CHECK(filesystem::exists(ott.file_name);
    }

    SUBCASE("Creates a database record") {
        auto query = "SELECT * FROM objects WHERE id = " + ott.id";
        // Get query, check it exists
    }  
}
```

So, the stuff in the top level of `TEST_CASE`, I only want to run once. However, the equivalent above code will run it twice (once for each test case). What is the method for writing a single setup method that will run only once and then run a bunch of sub cases? For example, in the Python `unittest` framework, you write a `_set_up` method that does all the setup stuff. I'm looking for an equivalent in doctest.

Thank you!

**Comment by onqtam** [comment]
hmmm, doctest doesn't provide anything out of the box for this, but you could just use a local `static` variable which will get initialized only once because its static.

**Comment by erik-whiting** [comment]
Thank you for your help! I'll close this issue now
