### ISSUE TITLE
Catch segfault signal?

### ISSUE THREAD

**Issue by jermp** [doctest/doctest#776]
Hello and thank you for this excellent library!

Is it possible to catch a segfault signal in a test and do not skip the tests coming after?

Many thanks in advance!
-Giulio

**Comment by dargueta** [comment]
Reliably, no. You would need to trap it with a signal handler, which is possible, but what happens after the signal handler returns  is implementation-defined and cannot be relied upon to work for everyone. Even linking to a different version of the standard C++ library on the same machine may break it.

> The following limitations are imposed on the user-defined function that is installed as a signal handler.
>
> If the user defined function returns when handling SIGFPE, SIGILL or SIGSEGV, the behavior is undefined.

 [Source](https://en.cppreference.com/w/c/program/signal)

**Comment by jermp** [comment]
Yeah...as I expected. Ok, thank you very much for confirming.
Best,
-Giulio
