### ISSUE TITLE
Documentation Enhancement: Add build2 to the list of supported build systems and package managers

### ISSUE THREAD

**Issue by lyrahgames** [doctest/doctest#787]
## Description

[build2](https://build2.org/) is a growing C/C++ build toolchain that already supports the importation of doctest via its [official package repository](https://cppget.org/doctest) and [GitHub](https://github.com/build2-packaging/doctest).
Thus, it would be beneficial to also add this information to the documentation in `doc/markdown/build-systems.md` together with its basic usage, like it was done [here](https://github.com/build2-packaging/doctest/blob/master/README.md#Usage).
Additionally, I would consider a usage example in `examples/doctest_build2/` as it was done for CMake in `examples/installed_doctest_cmake/` to be very helpful.
Also, I would offer to add the stated information to the documentation myself by a pull request. Referring to the contribution guidelines, this issue is only meant to get the confirmation and make this contribution go smoothly.
Thank you all so much for your hard work!

**Comment by cdeln** [comment]
Hi @lyrahgames . I think it's a great idea,. Sorry for staled issue, hope you still want to contribute.

**Comment by lyrahgames** [comment]
Hi @cdeln , no problem. Yes, I still want to contribute. Please see pull request #788 . There I have already added some information.

**Comment by cdeln** [comment]
Ah missed that PR, thanks!

@Saalvage I think this should be merged.
