### ISSUE TITLE
Feature Request : Is there a way to access the list of tests programatically

### ISSUE THREAD

**Issue by ronniec95** [doctest/doctest#79]
In a GUI based tool, it's useful to be able to interactively run tests. Is there an programmatic way to retrieve the list of tests and run them.

Something like this?
```
for(const auto& test : ctx.list_of_tests()) {
...
     const auto& args = test.args();
...
     test.run();
}
```

Use case:
1. UI behaviour tests
2. Live debugging, where you are following a set of steps that a user submitted to reproduce a bug condition. You can use the UI to get to a particular state and then trigger the test.

**Comment by onqtam** [comment]
What can be hacked currently is the following:

```c++
// needed forward declaration if doctest is not implemented in this .cpp file
namespace doctest { namespace detail {
    std::set<TestCase>& getRegisteredTests();
}}

int main(int argc, char** argv) {
    doctest::Context ctx(argc, argv);
    
    int return_code = 0;
    
    const auto& all_tests = doctest::detail::getRegisteredTests();
    for(const auto& test : all_tests) {
        ctx.clearFilters();
        ctx.addFilter("test-case", test.m_name);
        return_code |= ctx.run();
    }
    
    return return_code;
}

TEST_CASE("asd1") { printf("asd1\n"); }
TEST_CASE("asd2") { printf("asd2\n"); }
TEST_CASE("asd3") { printf("asd3\n"); }
```

Drawbacks of this method:
- requires unique names for test cases - an alternative might be to use the ```first```/```last``` options to the context
- suboptimal - some startup code is executed a bunch of times
- prints the summary about executed tests a bunch of times

This might be possible in a much cleaner way after future refactoring of the library internals...

**Comment by ronniec95** [comment]
This is perfectly fine for now. I look forward to the cleaned up version
Thank you

**Comment by cdeln** [comment]
Closing due to existing solution.
