### ISSUE TITLE
Feature suggestion: memory leak detection

### ISSUE THREAD

**Issue by martinmoene** [doctest/doctest#80]
See CppUTest's [memory leak detection](http://cpputest.github.io/manual.html#memory_leak_detection).

**Comment by onqtam** [comment]
I was thinking about this in the past and decided to skip it for now - tools such as valgrind/drmemory or the sanitizers work pretty well so I consider this an orthogonal problem to testing... But I'll keep the issue open in case I change my mind :)

**Comment by cdeln** [comment]
I agree with @onqtam , there are many other tools that complement doctest in this respect.

I suggest we close this.
