### ISSUE TITLE
compiling with fastmath std::isnan(value)^flipped always evaluates to false

### ISSUE THREAD

**Issue by crroush** [doctest/doctest#815]
## Description

 warning: comparison with NaN always evaluates to false in fast floating point modes [-Wtautological-constant-compare]
    return std::isnan(value) ^ flipped

### Steps to reproduce

include doctest.h
enable fastmath
using intel 2022.2.1 oneapi ICPX compiler

### Extra information

* doctest version: 2.4.11
* Operating System:  centos 7
* Compiler+version:  icpx 2022.2.1 (oneapi)

**Comment by cdeln** [comment]
Comparing against a NaN always yields false.
If you still think this is a bug, then please provide a minimal reproducible example.
