### ISSUE TITLE
Doctest segfault with CHECK in implement w/o main

### ISSUE THREAD

**Issue by tyqualters** [doctest/doctest#818]
## Description

Trying to write an executable unit test for a shared library project. Using definitions like `CHECK ( ... )` and `FAIL ( ... )` outside of `TEST_CASE ( ... ) { ... }` result in a SEGFAULT.

[My StackOverflow question.](https://stackoverflow.com/questions/77207652/doctest-segfault-in-main-function)

### Steps to reproduce

1. Include doctest using vcpkg and cmake
2. In a unit test, write a test that doesn't implement main (`#define DOCTEST_CONFIG_IMPLEMENT`)
3. Add the doctest context and run it
4. Afterward try to use `CHECK( <test evaluation> )`
5. Debugger catches a SEGFAULT in doctest.h where the CHECK would be evaluating.

### Extra information

* doctest version: **v2.4.11**
* Operating System: **Arch Linux**
* Compiler+version: **GCC 13.2.1-3**

**Comment by onqtam** [comment]
You're not meant to do that by default. However, there's a way to use these macros like asserts - check this out: https://github.com/doctest/doctest/blob/master/doc/markdown/assertions.md#using-asserts-out-of-a-testing-context
