### ISSUE TITLE
Warning from new CMake

### ISSUE THREAD

**Issue by mhhollomon** [doctest/doctest#829]
## Description
Starting to see the following warnings when using recent CMake versions.

```
CMake Deprecation Warning at build/_deps/doctest-src/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```

### Steps to reproduce
Install CMake version 3.27.7

Configure a build on the repo

### Extra information

* doctest version: **v2.4.11**
* Operating System: **Debian Testing**
* Compiler+version: **N/A**
* CMake Version : 3.27.7

**Comment by a4z** [comment]
same here

**Comment by gunvirranu** [comment]
Seeing same issue with CMake 3.28.1 on MacOS 14.0 with doctest version v2.4.8.

**Comment by onqtam** [comment]
fixed by this:
https://github.com/doctest/doctest/pull/811
