### ISSUE TITLE
TYPE_TO_STRING does not work inside a TEST_SUITE / namespace

### ISSUE THREAD

**Issue by anton-potapov** [doctest/doctest#847]
## Description
usage of macro fails with an error:
```error: ‘String’ does not name a type```

### Steps to reproduce
reproducer:
```c++
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"

TEST_SUITE(""){

TYPE_TO_STRING(short);
// TYPE_TO_STRING_AS("Int", int);

}
```
live at [godbolt.org](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:9,positionColumn:1,positionLineNumber:1,selectionStartColumn:2,selectionStartLineNumber:9,startColumn:1,startLineNumber:1),source:'%23define+DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN%0A%23include+%22doctest.h%22%0A%0ATEST_SUITE(%22%22)%7B%0A%0ATYPE_TO_STRING(short)%3B%0A//+TYPE_TO_STRING_AS(%22Int%22,+int)%3B%0A%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:53.97443023902168,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:clang1701,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:c%2B%2B,libs:!((name:doctest,ver:trunk)),options:'-O3+-std%3Dc%2B%2B20',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+17.0.1+(Editor+%231)',t:'0')),k:33.33333333333333,l:'4',m:35.554812058480024,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:2,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+17.0.1+(Compiler+%232)',t:'0')),header:(),l:'4',m:64.44518794151998,n:'0',o:'',s:0,t:'0')),k:46.02556976097832,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

### Extra information

* doctest version: **v2.4.11**
* Operating System: **Ubuntu 22.04.3 LTS**
* Compiler+version: **gcc version 12.3.0 (Ubuntu 12.3.0-1ubuntu1~22.04)**

**Comment by onqtam** [comment]
Why would you not use it in global scope?

**Comment by anton-potapov** [comment]
> Why would you not use it in global scope - as it's meant to be used?

Idea is not to pollute global namespace with test suite local names. Both to avoid name clashes , and simplify understanding of the test code (via reducing scope of names)

**Comment by cdeln** [comment]
This is not possible to do. `TEST_SUITE` defines an "opaque namespace" (that is, a generated, non user visible namespace).

The following code

```cpp
TEST_SUITE("RandomIterator") {
    struct random_iterator {};
    TYPE_TO_STRING(random_iterator);
}
```
expands into something like
```cpp
namespace DOCTEST_ANON_SUITE_2 {
   struct random_iterator {};
   namespace doctest {
   namespace detail {
   template <> inline const char* type_to_string<random_iterator>() {
       return "<" "random_iterator" ">";
   }
   } // detail
   } // doctest
   static_assert(true, "")                                         ;
} // DOCTEST_ANON_SUITE_2
```

which is an explicit template instantiation in the wrong namespace `DOCTEST_ANON_SUITE_2::doctest::detail`.
I suggest you rewrite tests requiring test suite specific types as follows

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

namespace testing {
    struct random_iterator {};
}

TYPE_TO_STRING(::testing::random_iterator);

TEST_SUITE("RandomIterator") {}
```

I am curious why you use test suite specific types to begin with, but I guess there is an use case ;)

**Comment by anton-potapov** [comment]
@cdeln as you said, this is not possible with _current_ approach of specializing template function. However this _is_ possible with function overloading( and [ADL ](https://en.cppreference.com/w/cpp/language/adl)) approach. 

This approach implies different call style of `toString` function (in library internals). 
i.e. changing `toString<SomeType>()` to `toString( std::type_identity<SomeTupe>{} )` 

`TYPE_TO_STRING` then would be defined like this : 
```c++
#define DOCTEST_TYPE_TO_STRING_AS(str, ...)                                                      \
        inline doctest::String toString( std::type_identity<__VA_ARGS__>{} ) {                   \
            return str;                                                                          \
        }                                                                                        \
    static_assert(true, "")

#define DOCTEST_TYPE_TO_STRING(...) DOCTEST_TYPE_TO_STRING_AS(#__VA_ARGS__, __VA_ARGS__)
```
