### ISSUE TITLE
Cosine becomes non-deterministic in unit test

### ISSUE THREAD

**Issue by cdeln** [doctest/doctest#863]
## Description
I've run into a bizarre bug. I have a unit test which basically just checks that `c == cos(x)`, where `c = cos(x)`. Inlining it as `cos(x) == cos(x)` does not make it fail.

### Steps to reproduce
Put this code into `main.cpp` and compile with `g++ -fPIC -O1 main.cpp`.
```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>
#include <random>

TEST_CASE("gcc-cos-sin-fpic-O1-bug")
{
    std::mt19937 g(0);
    std::normal_distribution<double> d(0.0, 1.0);
    for (int i = 0; i < 1000; ++i)
    {
        const double a = d(g);
        const double s = sin(a);
        const double c = cos(a);
        INFO(i);
        REQUIRE(s == sin(a));
        REQUIRE(c == cos(a));
        REQUIRE(a == a);
    }
}
```

Running `./a.out` I get the following output
```console
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
===============================================================================
main.cpp:5:
TEST CASE:  gcc-cos-sin-fpic-O1-bug

main.cpp:16: FATAL ERROR: REQUIRE( c == cos(a) ) is NOT correct!
  values: REQUIRE( -0.1912064051 == -0.1912064051 )
  logged: 833

===============================================================================
[doctest] test cases:    1 |    0 passed | 1 failed | 0 skipped
[doctest] assertions: 2501 | 2500 passed | 1 failed |
[doctest] Status: FAILURE!
```

Note that the test does not fail if you omit any of the flags.

### Extra information
* doctest version: **2.4.8~ds-1** (distributed with Ubuntu)
* Operating System: **Ubuntu 22.04.2 LTS**
* Compiler+version: **g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0** (distributed with Ubuntu)

**Comment by cdeln** [comment]
Edit: You can actually omit `-fPIC` compile flag, compiling with optimization `-O1` suffice to reproduce the bug.

**Comment by onqtam** [comment]
What would happen if you weren't using doctest at all but simple if statements?

**Comment by cdeln** [comment]
This runs fine (compiled with `g++ -O1`)

```cpp
#include <cassert>
#include <random>
#include <stdexcept>

#define REQUIRE(statement) if (!(statement)) throw std::runtime_error(#statement)

int main()
{
    std::mt19937 g(0);
    std::normal_distribution<double> d(0.0, 1.0);
    for (int i = 0; i < 100000000; ++i)
    {
        const double a = d(g);
        const double s = sin(a);
        const double c = cos(a);
        REQUIRE(s == sin(a));
        REQUIRE(c == cos(a));
        REQUIRE(a == a);
    }
}
```

**Comment by cdeln** [comment]
Further down the rabbit hole... 
Compiled without optimizations and full debug info: `g++ -Wall -Wextra -Werror -Wpedantic -Og -g3` 

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("gcc-cos-bug")
{
    const double a = 1.2475784324341769;
    const double c = cos(a);
    REQUIRE(c == cos(a));
}
```

**Comment by onqtam** [comment]
Seems you've found something worth investigating!

However, I won't be able to help with this issue anytime soon (if ever - #554 )

**Comment by cdeln** [comment]
I've seen so, cool to see you still hanging around ;)

Anyways, this does not seem to be a doctest issue at all, more likely a GCC bug (or there is some intricate part of the standard that is being overlooked somehow...)
The following program fails

```cpp
#include <cmath>
#include <stdexcept>

#define REQUIRE(statement) if (!(statement)) throw std::runtime_error(#statement)

int main()
{
    const double a = 1.2475784324341769;
    const double c = cos(a);
    [&] {
        REQUIRE(a == a);
        REQUIRE(c == cos(a));
    }();
}
```

Something about the lambda going on there.

**Comment by cdeln** [comment]
Filed a bug to GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116331

Long story short, this issue is very intricate and is most likely related to something called "excessive precision", which can make any floating point math non-deterministic on x86 family of processors. For the interested reader, read up on the infamous bug 323 in GCC.

I believe the reduced test case fails due to some weirdness in constant folding done by the compiler. However, the original bug in this thread can impossibly be due to that (unless GCC do some weird constant folding of random number generators... I hope that is not the case!). I'll keep posting updates as I make progress on the issue, I don't expect anyone to comment on it, just for documentation purposes.

**Comment by cdeln** [comment]
This is actually not related to excess precision! The reduced test case with the hard coded literal made GCC optimize some calculations at compile time outside the lambda, but the calls inside are compiled into library calls. Hence there are 2 different `cos` at play here!

Now, the original bug is obviously not related to constant folding. Digged into the assembly a bit and discovered that GCC optimize the paired `cos` and `sin` into a non-standard `sincos`. So the issue is that the vales outside `REQUIRE` are computed using `sincos`, but the `sin` and `cos` in the `REQUIRE` macro will be evaluated in separate lexical contexts which does not allow for this optimization to happen. I am now pursuing this path, starting with a bug report to the package maintainers of glibc on Ubuntu: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/2076653 .

It's interesting how exactly the same double value could trigger two completely different bugs in GCC/glibc! And I start to realize that `==` is probably broken for floats (I discovered `-Wfloat-equal` in GCC, I will probably start using this in all my code from now on...). 

Reading up again on the reference for handling floats in test cases in doctest: https://github.com/doctest/doctest/blob/master/doc/markdown/assertions.md#floating-point-comparisons , I use `doctest::Approx` a lot, but I never use it where I really expect `==` to hold. Is there a way to compare floating point values with an error specified in ULP instead of relative error using `epsilon`? Ideally I would like to assert something like this

    REQUIRE(cos(a) == Approx(c).ulp(1))
