### ISSUE TITLE
Typo in examples/all_features/CMakeLists.txt

### ISSUE THREAD

**Issue by UnePierre** [doctest/doctest#877]
## Description

There is probably a copy&paste error in:
https://github.com/doctest/doctest/blob/35a540d01395117c733125aa7d1781b37b40d077/examples/all_features/CMakeLists.txt#L66
```
doctest_add_test(NO_OUTPUT NAME bitfield_packed_struct.cpp ${common_args} -sf=*bitfield_packed_struct.cpp.cpp )
                                                                                                         ^^^^
```
See the double `.cpp`?

**Comment by onqtam** [comment]
merged! Thanks.
